//
// Generated by Bluespec Compiler, version 2019.05.beta2 (build a88bf40db, 2019-05-24)
//
// On Wed Jun 17 12:21:07 BST 2020
//
//
// Ports:
// Name                         I/O  size props
// basicExec                      O  1160
// basicExec_dInst                I   144
// basicExec_rVal1                I   163
// basicExec_rVal2                I   163
// basicExec_pcc                  I   163
// basicExec_ppc                  I   163
// basicExec_orig_inst            I    32
//
// Combinational paths from inputs to outputs:
//   (basicExec_dInst,
//    basicExec_rVal1,
//    basicExec_rVal2,
//    basicExec_pcc,
//    basicExec_ppc,
//    basicExec_orig_inst) -> basicExec
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_basicExec(basicExec_dInst,
			basicExec_rVal1,
			basicExec_rVal2,
			basicExec_pcc,
			basicExec_ppc,
			basicExec_orig_inst,
			basicExec);
  // value method basicExec
  input  [143 : 0] basicExec_dInst;
  input  [162 : 0] basicExec_rVal1;
  input  [162 : 0] basicExec_rVal2;
  input  [162 : 0] basicExec_pcc;
  input  [162 : 0] basicExec_ppc;
  input  [31 : 0] basicExec_orig_inst;
  output [1159 : 0] basicExec;

  // signals for module outputs
  wire [1159 : 0] basicExec;

  // remaining internal signals
  reg [162 : 0] IF_basicExec_dInst_BITS_143_TO_139_EQ_5_OR_bas_ETC___d688;
  reg [65 : 0] IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d327,
	       addr_capFat_address__h4841;
  reg [33 : 0] CASE_basicExec_dInst_BITS_143_TO_139_2_1402575_ETC__q3,
	       IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_1_ETC___d597;
  reg [17 : 0] IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_2_ETC___d567;
  reg [13 : 0] IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d350,
	       addr_capFat_addrBits__h4842;
  reg [4 : 0] CASE_capChecks_68_BITS_4_TO_0_0_capChecks_68_B_ETC__q6;
  reg [3 : 0] CASE_IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_ETC__q5,
	      CASE_basicExec_dInst_BITS_143_TO_139_2_0_4_0_5_ETC__q4,
	      IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35,
	      IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d364,
	      IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d684,
	      addr_capFat_perms_soft__h4865;
  reg [2 : 0] CASE_IF_basicExec_dInst_BITS_102_TO_100_44_EQ__ETC__q2,
	      IF_basicExec_dInst_BITS_102_TO_100_44_EQ_2_48__ETC___d151,
	      IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_7_ETC___d613,
	      addr_tempFields_repBoundTopBits__h4939;
  reg [1 : 0] IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d554,
	      addr_capFat_reserved__h4845;
  reg CASE_basicExec_dInst_BITS_143_TO_139_11_res_fs_ETC__q7,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d258,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d377,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d390,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d403,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d416,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d429,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d442,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d455,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d468,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d481,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d494,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d507,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d520,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d583,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d627,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d640,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d655,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d254,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d374,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d387,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d400,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d413,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d426,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d439,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d452,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d465,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d478,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d491,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d504,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d517,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d536,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d579,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d623,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d636,
      IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d651;
  wire [606 : 0] basicExec_pcc_CONCAT_brAddrCalc_45_BITS_162_TO_ETC___d939;
  wire [265 : 0] prepareBoundsCheck___d931;
  wire [163 : 0] capModify___d197;
  wire [162 : 0] IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d859,
		 NOT_basicExec_dInst_BITS_143_TO_139_EQ_4_29_30_ETC___d781,
		 NOT_basicExec_dInst_BIT_32_4_5_AND_IF_basicExe_ETC___d727,
		 brAddrCalc___d245,
		 specialRWALU___d728;
  wire [151 : 0] IF_basicExec_dInst_BIT_32_4_THEN_0_CONCAT_SEXT_ETC___d719;
  wire [127 : 0] x__h5490, y__h5491;
  wire [71 : 0] IF_basicExec_dInst_BIT_32_4_THEN_0_ELSE_IF_bas_ETC___d718;
  wire [65 : 0] _theResult___snd_capFat_address__h876,
		aluVal2_capFat_address__h1258,
		in__h2645,
		in__h2959,
		pointer__h490,
		pointer__h526,
		res_address__h460,
		res_address__h504,
		res_address__h515,
		res_address__h888,
		res_fst_capFat_address__h479,
		result_d_address__h849,
		x__h2522,
		x__h2977,
		x__h3081,
		y__h2976;
  wire [63 : 0] addr__h384,
		addr__h4016,
		addr__h403,
		addr__h407,
		address__h398,
		alu_result__h35,
		x__h2512,
		x__h2514,
		x__h2923,
		x__h2925,
		x__h771;
  wire [54 : 0] IF_basicExec_dInst_BITS_143_TO_139_EQ_4_29_OR__ETC___d771,
		IF_basicExec_dInst_BIT_32_4_THEN_0_ELSE_IF_bas_ETC___d717;
  wire [49 : 0] highBitsfilter__h534,
		highOffsetBits__h535,
		signBits__h532,
		x__h562;
  wire [45 : 0] basicExec_dInst_BITS_97_TO_74_60_CONCAT_IF_bas_ETC___d865;
  wire [33 : 0] IF_basicExec_dInst_BITS_108_TO_107_0_EQ_0_1_TH_ETC___d586,
		IF_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AN_ETC___d110,
		IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d590;
  wire [31 : 0] basicExec_dInst_BITS_31_TO_0__q1;
  wire [25 : 0] IF_basicExec_ppc_BIT_44_18_THEN_basicExec_ppc__ETC___d826,
		IF_brAddrCalc_45_BIT_44_71_THEN_brAddrCalc_45__ETC___d800;
  wire [17 : 0] _theResult___snd_capFat_otype__h881,
		aluVal2_capFat_otype__h1263,
		res_fst_capFat_otype__h484;
  wire [15 : 0] base__h2499, base__h2910, offset__h2500, offset__h2911;
  wire [13 : 0] _theResult___snd_capFat_addrBits__h877,
		aluVal2_capFat_addrBits__h1259,
		repBoundBits__h541,
		res_addrBits__h461,
		res_addrBits__h505,
		res_addrBits__h516,
		res_addrBits__h889,
		res_fst_capFat_addrBits__h480,
		toBoundsM1__h545,
		toBounds__h544;
  wire [11 : 0] capChecks___d868, inc__h397;
  wire [8 : 0] IF_basicExec_dInst_BITS_106_TO_103_4_EQ_0_5_OR_ETC___d196,
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_1_7_OR_ETC___d195,
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_2_9_OR_ETC___d194;
  wire [6 : 0] basicExec_dInst_BIT_32_4_OR_IF_basicExec_dInst_ETC___d726;
  wire [4 : 0] IF_basicExec_dInst_BITS_102_TO_100_44_EQ_0_45__ETC___d166;
  wire [3 : 0] IF_basicExec_dInst_BITS_108_TO_107_0_EQ_0_1_TH_ETC___d659,
	       IF_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AN_ETC___d124,
	       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d677,
	       IF_basicExec_pcc_BITS_37_TO_35_16_ULT_basicExe_ETC___d664,
	       IF_basicExec_pcc_BITS_37_TO_35_16_ULT_basicExe_ETC___d674,
	       _theResult___snd_capFat_perms_soft__h3135,
	       aluVal2_capFat_perms_soft__h1320,
	       res_fst_capFat_perms_soft__h3129;
  wire [2 : 0] _theResult___snd_tempFields_repBoundTopBits__h3672,
	       aluVal2_tempFields_repBoundTopBits__h1631,
	       repBound__h3653,
	       res_fst_tempFields_repBoundTopBits__h3623;
  wire [1 : 0] IF_basicExec_pcc_BITS_23_TO_21_70_ULT_basicExe_ETC___d279,
	       _theResult___snd_capFat_reserved__h880,
	       aluVal2_capFat_reserved__h1262,
	       res_fst_capFat_reserved__h483;
  wire IF_SEXT_basicExec_dInst_BITS_31_TO_0_0_1_BIT_6_ETC___d229,
       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d248,
       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d371,
       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d384,
       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d397,
       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d410,
       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d423,
       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d436,
       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d449,
       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d462,
       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d475,
       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d488,
       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d501,
       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d514,
       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d573,
       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d620,
       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d633,
       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d648,
       NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d108,
       NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d118,
       NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d120,
       NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d122,
       NOT_basicExec_dInst_BIT_75_43_44_OR_basicExec__ETC___d852,
       _0_CONCAT_basicExec_pcc_BITS_159_TO_96_60_PLUS__ETC___d274,
       _theResult___snd_capFat_flags__h879,
       addr_capFat_flags__h4844,
       aluBr___d243,
       aluVal2_capFat_flags__h1261,
       basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d48,
       basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d61,
       basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d63,
       basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d65,
       basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d67,
       basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d69,
       basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d71,
       basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d73,
       basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d75,
       basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d77,
       basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d79,
       basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d81,
       basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d83,
       basicExec_pcc_BITS_161_TO_96_02_PLUS_0_CONCAT__ETC___d645,
       basicExec_pcc_BITS_23_TO_21_70_ULT_basicExec_p_ETC___d272,
       basicExec_pcc_BITS_37_TO_35_16_ULT_basicExec_p_ETC___d617,
       res_fst_capFat_flags__h482;

  // value method basicExec
  assign basicExec =
	     { IF_basicExec_dInst_BITS_143_TO_139_EQ_5_OR_bas_ETC___d688,
	       alu_result__h35,
	       specialRWALU___d728,
	       NOT_basicExec_dInst_BITS_143_TO_139_EQ_4_29_30_ETC___d781,
	       basicExec_pcc_CONCAT_brAddrCalc_45_BITS_162_TO_ETC___d939 } ;

  // remaining internal signals
  module_alu instance_alu_2(.alu_a(basicExec_rVal1[159:96]),
			    .alu_b(aluVal2_capFat_address__h1258[63:0]),
			    .alu_func((basicExec_dInst[138:136] == 3'd0) ?
					basicExec_dInst[113:109] :
					5'd0),
			    .alu(alu_result__h35));
  module_aluBr instance_aluBr_0(.aluBr_a(basicExec_rVal1[159:96]),
				.aluBr_b(basicExec_rVal2[159:96]),
				.aluBr_brFunc((basicExec_dInst[138:136] ==
					       3'd1) ?
						basicExec_dInst[111:109] :
						3'd7),
				.aluBr(aluBr___d243));
  module_brAddrCalc instance_brAddrCalc_5(.brAddrCalc_pc(basicExec_pcc),
					  .brAddrCalc_val(basicExec_rVal1),
					  .brAddrCalc_iType(basicExec_dInst[143:139]),
					  .brAddrCalc_imm(basicExec_dInst[32] ?
							    addr__h4016 :
							    64'd0),
					  .brAddrCalc_taken(aluBr___d243),
					  .brAddrCalc_orig_inst(basicExec_orig_inst),
					  .brAddrCalc_cap(basicExec_dInst[143:139] ==
							  5'd12 ||
							  basicExec_dInst[143:139] ==
							  5'd11),
					  .brAddrCalc(brAddrCalc___d245));
  module_capInspect instance_capInspect_3(.capInspect_a(basicExec_rVal1),
					  .capInspect_b({ basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d48,
							  { aluVal2_capFat_address__h1258,
							    aluVal2_capFat_addrBits__h1259,
							    { aluVal2_capFat_perms_soft__h1320,
							      { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d61,
								basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d63,
								{ basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d65,
								  basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d67,
								  { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d69,
								    basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d71,
								    { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d73,
								      basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d75,
								      { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d77,
									basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d79,
									{ basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d81,
									  basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d83 } } } } } },
							      aluVal2_capFat_flags__h1261,
							      { aluVal2_capFat_reserved__h1262,
								aluVal2_capFat_otype__h1263,
								{ NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d108,
								  IF_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AN_ETC___d110 } } } },
							  aluVal2_tempFields_repBoundTopBits__h1631,
							  { NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d118,
							    NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d120,
							    { NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d122,
							      IF_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AN_ETC___d124 } } }),
					  .capInspect_func(basicExec_dInst[101:98]),
					  .capInspect(addr__h384));
  module_prepareBoundsCheck instance_prepareBoundsCheck_7(.prepareBoundsCheck_a(IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d859),
							  .prepareBoundsCheck_b({ basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d48,
										  { aluVal2_capFat_address__h1258,
										    aluVal2_capFat_addrBits__h1259,
										    { aluVal2_capFat_perms_soft__h1320,
										      { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d61,
											basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d63,
											{ basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d65,
											  basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d67,
											  { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d69,
											    basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d71,
											    { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d73,
											      basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d75,
											      { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d77,
												basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d79,
												{ basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d81,
												  basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d83 } } } } } },
										      aluVal2_capFat_flags__h1261,
										      { aluVal2_capFat_reserved__h1262,
											aluVal2_capFat_otype__h1263,
											{ NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d108,
											  IF_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AN_ETC___d110 } } } },
										  aluVal2_tempFields_repBoundTopBits__h1631,
										  { NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d118,
										    NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d120,
										    { NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d122,
										      IF_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AN_ETC___d124 } } }),
							  .prepareBoundsCheck_pcc(basicExec_pcc),
							  .prepareBoundsCheck_ddc(163'h00000000000000000000000007FFFFD10000003F0),
							  .prepareBoundsCheck_vaddr(64'd0),
							  .prepareBoundsCheck_size(5'd0),
							  .prepareBoundsCheck_toCheck(basicExec_dInst_BITS_97_TO_74_60_CONCAT_IF_bas_ETC___d865),
							  .prepareBoundsCheck(prepareBoundsCheck___d931));
  module_specialRWALU instance_specialRWALU_4(.specialRWALU_cap(NOT_basicExec_dInst_BIT_32_4_5_AND_IF_basicExe_ETC___d727),
					      .specialRWALU_oldCap(basicExec_rVal2),
					      .specialRWALU_scrType(IF_basicExec_dInst_BITS_102_TO_100_44_EQ_0_45__ETC___d166),
					      .specialRWALU(specialRWALU___d728));
  module_capModify instance_capModify_6(.capModify_a(basicExec_rVal1),
					.capModify_b({ basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d48,
						       { aluVal2_capFat_address__h1258,
							 aluVal2_capFat_addrBits__h1259,
							 { aluVal2_capFat_perms_soft__h1320,
							   { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d61,
							     basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d63,
							     { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d65,
							       basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d67,
							       { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d69,
								 basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d71,
								 { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d73,
								   basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d75,
								   { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d77,
								     basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d79,
								     { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d81,
								       basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d83 } } } } } },
							   aluVal2_capFat_flags__h1261,
							   { aluVal2_capFat_reserved__h1262,
							     aluVal2_capFat_otype__h1263,
							     { NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d108,
							       IF_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AN_ETC___d110 } } } },
						       aluVal2_tempFields_repBoundTopBits__h1631,
						       { NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d118,
							 NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d120,
							 { NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d122,
							   IF_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AN_ETC___d124 } } }),
					.capModify_func(IF_basicExec_dInst_BITS_106_TO_103_4_EQ_0_5_OR_ETC___d196),
					.capModify(capModify___d197));
  module_capChecks instance_capChecks_1(.capChecks_a(IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d859),
					.capChecks_b({ basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d48,
						       { aluVal2_capFat_address__h1258,
							 aluVal2_capFat_addrBits__h1259,
							 { aluVal2_capFat_perms_soft__h1320,
							   { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d61,
							     basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d63,
							     { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d65,
							       basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d67,
							       { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d69,
								 basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d71,
								 { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d73,
								   basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d75,
								   { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d77,
								     basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d79,
								     { basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d81,
								       basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d83 } } } } } },
							   aluVal2_capFat_flags__h1261,
							   { aluVal2_capFat_reserved__h1262,
							     aluVal2_capFat_otype__h1263,
							     { NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d108,
							       IF_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AN_ETC___d110 } } } },
						       aluVal2_tempFields_repBoundTopBits__h1631,
						       { NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d118,
							 NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d120,
							 { NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d122,
							   IF_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AN_ETC___d124 } } }),
					.capChecks_ddc(163'h00000000000000000000000007FFFFD10000003F0),
					.capChecks_toCheck(basicExec_dInst_BITS_97_TO_74_60_CONCAT_IF_bas_ETC___d865),
					.capChecks_cap_exact(capModify___d197[0]),
					.capChecks(capChecks___d868));
  assign IF_SEXT_basicExec_dInst_BITS_31_TO_0_0_1_BIT_6_ETC___d229 =
	     addr__h4016[63] ?
	       x__h771[13:0] >= toBounds__h544 &&
	       repBoundBits__h541 != basicExec_pcc[95:82] :
	       x__h771[13:0] < toBoundsM1__h545 ;
  assign IF_basicExec_dInst_BITS_102_TO_100_44_EQ_0_45__ETC___d166 =
	     (basicExec_dInst[102:100] == 3'd0 ||
	      basicExec_dInst[102:100] != 3'd1 &&
	      IF_basicExec_dInst_BITS_102_TO_100_44_EQ_2_48__ETC___d151 ==
	      3'd0) ?
	       { 3'd0, basicExec_dInst[99:98] } :
	       ((basicExec_dInst[102:100] == 3'd1 ||
		 IF_basicExec_dInst_BITS_102_TO_100_44_EQ_2_48__ETC___d151 ==
		 3'd1) ?
		  { 3'd1, basicExec_dInst[99:98] } :
		  { CASE_IF_basicExec_dInst_BITS_102_TO_100_44_EQ__ETC__q2,
		    2'h2 }) ;
  assign IF_basicExec_dInst_BITS_106_TO_103_4_EQ_0_5_OR_ETC___d196 =
	     (basicExec_dInst[106:103] == 4'd0 ||
	      basicExec_dInst[106:103] != 4'd1 &&
	      basicExec_dInst[106:103] != 4'd2 &&
	      basicExec_dInst[106:103] != 4'd3 &&
	      basicExec_dInst[106:103] != 4'd4 &&
	      basicExec_dInst[106:103] != 4'd5 &&
	      IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	      4'd0) ?
	       { 4'd0, basicExec_dInst[102:98] } :
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_1_7_OR_ETC___d195 ;
  assign IF_basicExec_dInst_BITS_106_TO_103_4_EQ_1_7_OR_ETC___d195 =
	     (basicExec_dInst[106:103] == 4'd1 ||
	      basicExec_dInst[106:103] != 4'd2 &&
	      basicExec_dInst[106:103] != 4'd3 &&
	      basicExec_dInst[106:103] != 4'd4 &&
	      basicExec_dInst[106:103] != 4'd5 &&
	      IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	      4'd1) ?
	       { 4'd1, basicExec_dInst[102:98] } :
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_2_9_OR_ETC___d194 ;
  assign IF_basicExec_dInst_BITS_106_TO_103_4_EQ_2_9_OR_ETC___d194 =
	     (basicExec_dInst[106:103] == 4'd2 ||
	      basicExec_dInst[106:103] != 4'd3 &&
	      basicExec_dInst[106:103] != 4'd4 &&
	      basicExec_dInst[106:103] != 4'd5 &&
	      IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	      4'd2) ?
	       { 4'd2,
		 IF_basicExec_dInst_BITS_102_TO_100_44_EQ_0_45__ETC___d166 } :
	       ((basicExec_dInst[106:103] == 4'd3 ||
		 basicExec_dInst[106:103] != 4'd4 &&
		 basicExec_dInst[106:103] != 4'd5 &&
		 IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
		 4'd3) ?
		  { 4'd3, basicExec_dInst[102:98] } :
		  ((basicExec_dInst[106:103] == 4'd4 ||
		    basicExec_dInst[106:103] != 4'd5 &&
		    IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
		    4'd4) ?
		     9'd138 :
		     ((basicExec_dInst[106:103] == 4'd5 ||
		       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
		       4'd5) ?
			{ 4'd5, basicExec_dInst[102:98] } :
			{ CASE_IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_ETC__q5,
			  5'h0A }))) ;
  assign IF_basicExec_dInst_BITS_108_TO_107_0_EQ_0_1_TH_ETC___d586 =
	     (basicExec_dInst[108:107] == 2'd0) ?
	       34'h344000000 :
	       capModify___d197[44:11] ;
  assign IF_basicExec_dInst_BITS_108_TO_107_0_EQ_0_1_TH_ETC___d659 =
	     (basicExec_dInst[108:107] == 2'd0) ?
	       {2{basicExec_dInst[108:107]}} :
	       capModify___d197[4:1] ;
  assign IF_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AN_ETC___d110 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) ?
	       basicExec_rVal2[43:10] :
	       34'h344000000 ;
  assign IF_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AN_ETC___d124 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) ?
	       basicExec_rVal2[3:0] :
	       4'd0 ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d248 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[162] :
	       basicExec_rVal1[162] ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d371 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[77] :
	       basicExec_rVal1[77] ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d384 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[76] :
	       basicExec_rVal1[76] ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d397 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[75] :
	       basicExec_rVal1[75] ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d410 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[74] :
	       basicExec_rVal1[74] ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d423 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[73] :
	       basicExec_rVal1[73] ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d436 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[72] :
	       basicExec_rVal1[72] ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d449 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[71] :
	       basicExec_rVal1[71] ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d462 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[70] :
	       basicExec_rVal1[70] ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d475 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[69] :
	       basicExec_rVal1[69] ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d488 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[68] :
	       basicExec_rVal1[68] ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d501 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[67] :
	       basicExec_rVal1[67] ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d514 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[66] :
	       basicExec_rVal1[66] ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d573 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[44] :
	       basicExec_rVal1[44] ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d590 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[43:10] :
	       basicExec_rVal1[43:10] ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d620 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[6] :
	       basicExec_rVal1[6] ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d633 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[5] :
	       basicExec_rVal1[5] ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d648 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[4] :
	       basicExec_rVal1[4] ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d677 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[3:0] :
	       basicExec_rVal1[3:0] ;
  assign IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d859 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245 :
	       basicExec_rVal1 ;
  assign IF_basicExec_dInst_BITS_143_TO_139_EQ_4_29_OR__ETC___d771 =
	     { addr_capFat_reserved__h4845,
	       18'd262143,
	       basicExec_dInst[143:139] == 5'd4 ||
	       basicExec_dInst[143:139] == 5'd5 ||
	       basicExec_dInst[143:139] == 5'd6 ||
	       basicExec_dInst[143:139] == 5'd7 ||
	       basicExec_dInst[143:139] == 5'd2 ||
	       brAddrCalc___d245[44],
	       CASE_basicExec_dInst_BITS_143_TO_139_2_1402575_ETC__q3 } ;
  assign IF_basicExec_dInst_BIT_32_4_THEN_0_CONCAT_SEXT_ETC___d719 =
	     { basicExec_dInst[32] ?
		 { 2'd0, addr__h4016 } :
		 _theResult___snd_capFat_address__h876,
	       basicExec_dInst[32] ?
		 { 2'b0, addr__h4016[63:52] } :
		 _theResult___snd_capFat_addrBits__h877,
	       IF_basicExec_dInst_BIT_32_4_THEN_0_ELSE_IF_bas_ETC___d718 } ;
  assign IF_basicExec_dInst_BIT_32_4_THEN_0_ELSE_IF_bas_ETC___d717 =
	     { basicExec_dInst[32] ?
		 2'd0 :
		 _theResult___snd_capFat_reserved__h880,
	       basicExec_dInst[32] ?
		 18'd262143 :
		 _theResult___snd_capFat_otype__h881,
	       basicExec_dInst[32] ||
	       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d573,
	       basicExec_dInst[32] ?
		 34'h344000000 :
		 IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d590 } ;
  assign IF_basicExec_dInst_BIT_32_4_THEN_0_ELSE_IF_bas_ETC___d718 =
	     { basicExec_dInst[32] ?
		 4'd0 :
		 _theResult___snd_capFat_perms_soft__h3135,
	       !basicExec_dInst[32] &&
	       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d371,
	       !basicExec_dInst[32] &&
	       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d384,
	       !basicExec_dInst[32] &&
	       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d397,
	       !basicExec_dInst[32] &&
	       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d410,
	       !basicExec_dInst[32] &&
	       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d423,
	       !basicExec_dInst[32] &&
	       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d436,
	       !basicExec_dInst[32] &&
	       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d449,
	       !basicExec_dInst[32] &&
	       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d462,
	       !basicExec_dInst[32] &&
	       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d475,
	       !basicExec_dInst[32] &&
	       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d488,
	       !basicExec_dInst[32] &&
	       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d501,
	       !basicExec_dInst[32] &&
	       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d514,
	       !basicExec_dInst[32] && _theResult___snd_capFat_flags__h879,
	       IF_basicExec_dInst_BIT_32_4_THEN_0_ELSE_IF_bas_ETC___d717 } ;
  assign IF_basicExec_pcc_BITS_23_TO_21_70_ULT_basicExe_ETC___d279 =
	     (basicExec_pcc_BITS_23_TO_21_70_ULT_basicExec_p_ETC___d272 ==
	      _0_CONCAT_basicExec_pcc_BITS_159_TO_96_60_PLUS__ETC___d274) ?
	       2'd0 :
	       ((basicExec_pcc_BITS_23_TO_21_70_ULT_basicExec_p_ETC___d272 &&
		 !_0_CONCAT_basicExec_pcc_BITS_159_TO_96_60_PLUS__ETC___d274) ?
		  2'd1 :
		  2'd3) ;
  assign IF_basicExec_pcc_BITS_37_TO_35_16_ULT_basicExe_ETC___d664 =
	     { (basicExec_pcc_BITS_37_TO_35_16_ULT_basicExec_p_ETC___d617 ==
		_0_CONCAT_basicExec_pcc_BITS_159_TO_96_60_PLUS__ETC___d274) ?
		 2'd0 :
		 ((basicExec_pcc_BITS_37_TO_35_16_ULT_basicExec_p_ETC___d617 &&
		   !_0_CONCAT_basicExec_pcc_BITS_159_TO_96_60_PLUS__ETC___d274) ?
		    2'd1 :
		    2'd3),
	       IF_basicExec_pcc_BITS_23_TO_21_70_ULT_basicExe_ETC___d279 } ;
  assign IF_basicExec_pcc_BITS_37_TO_35_16_ULT_basicExe_ETC___d674 =
	     { (basicExec_pcc_BITS_37_TO_35_16_ULT_basicExec_p_ETC___d617 ==
		basicExec_pcc_BITS_161_TO_96_02_PLUS_0_CONCAT__ETC___d645) ?
		 2'd0 :
		 ((basicExec_pcc_BITS_37_TO_35_16_ULT_basicExec_p_ETC___d617 &&
		   !basicExec_pcc_BITS_161_TO_96_02_PLUS_0_CONCAT__ETC___d645) ?
		    2'd1 :
		    2'd3),
	       (basicExec_pcc_BITS_23_TO_21_70_ULT_basicExec_p_ETC___d272 ==
		basicExec_pcc_BITS_161_TO_96_02_PLUS_0_CONCAT__ETC___d645) ?
		 2'd0 :
		 ((basicExec_pcc_BITS_23_TO_21_70_ULT_basicExec_p_ETC___d272 &&
		   !basicExec_pcc_BITS_161_TO_96_02_PLUS_0_CONCAT__ETC___d645) ?
		    2'd1 :
		    2'd3) } ;
  assign IF_basicExec_ppc_BIT_44_18_THEN_basicExec_ppc__ETC___d826 =
	     basicExec_ppc[44] ?
	       { basicExec_ppc[35:27],
		 basicExec_ppc[43:41],
		 basicExec_ppc[23:13],
		 basicExec_ppc[40:38] } :
	       basicExec_ppc[35:10] ;
  assign IF_brAddrCalc_45_BIT_44_71_THEN_brAddrCalc_45__ETC___d800 =
	     brAddrCalc___d245[44] ?
	       { brAddrCalc___d245[35:27],
		 brAddrCalc___d245[43:41],
		 brAddrCalc___d245[23:13],
		 brAddrCalc___d245[40:38] } :
	       brAddrCalc___d245[35:10] ;
  assign NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d108 =
	     (basicExec_dInst[108:107] != 2'd1 ||
	      basicExec_dInst[106:103] == 4'd0 ||
	      basicExec_dInst[106:103] == 4'd1 ||
	      basicExec_dInst[106:103] != 4'd2 &&
	      (basicExec_dInst[106:103] == 4'd3 ||
	       basicExec_dInst[106:103] == 4'd4 ||
	       basicExec_dInst[106:103] == 4'd5 ||
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 !=
	       4'd2)) &&
	     basicExec_dInst[32] ||
	     basicExec_rVal2[44] ;
  assign NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d118 =
	     (basicExec_dInst[108:107] != 2'd1 ||
	      basicExec_dInst[106:103] == 4'd0 ||
	      basicExec_dInst[106:103] == 4'd1 ||
	      basicExec_dInst[106:103] != 4'd2 &&
	      (basicExec_dInst[106:103] == 4'd3 ||
	       basicExec_dInst[106:103] == 4'd4 ||
	       basicExec_dInst[106:103] == 4'd5 ||
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 !=
	       4'd2)) &&
	     basicExec_dInst[32] ||
	     basicExec_rVal2[6] ;
  assign NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d120 =
	     (basicExec_dInst[108:107] != 2'd1 ||
	      basicExec_dInst[106:103] == 4'd0 ||
	      basicExec_dInst[106:103] == 4'd1 ||
	      basicExec_dInst[106:103] != 4'd2 &&
	      (basicExec_dInst[106:103] == 4'd3 ||
	       basicExec_dInst[106:103] == 4'd4 ||
	       basicExec_dInst[106:103] == 4'd5 ||
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 !=
	       4'd2)) &&
	     basicExec_dInst[32] ||
	     basicExec_rVal2[5] ;
  assign NOT_basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_6_ETC___d122 =
	     (basicExec_dInst[108:107] != 2'd1 ||
	      basicExec_dInst[106:103] == 4'd0 ||
	      basicExec_dInst[106:103] == 4'd1 ||
	      basicExec_dInst[106:103] != 4'd2 &&
	      (basicExec_dInst[106:103] == 4'd3 ||
	       basicExec_dInst[106:103] == 4'd4 ||
	       basicExec_dInst[106:103] == 4'd5 ||
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 !=
	       4'd2)) &&
	     basicExec_dInst[32] ||
	     basicExec_rVal2[4] ;
  assign NOT_basicExec_dInst_BITS_143_TO_139_EQ_4_29_30_ETC___d781 =
	     { basicExec_dInst[143:139] != 5'd4 &&
	       basicExec_dInst[143:139] != 5'd5 &&
	       basicExec_dInst[143:139] != 5'd6 &&
	       basicExec_dInst[143:139] != 5'd7 &&
	       basicExec_dInst[143:139] != 5'd2 &&
	       brAddrCalc___d245[162],
	       addr_capFat_address__h4841,
	       addr_capFat_addrBits__h4842,
	       addr_capFat_perms_soft__h4865,
	       basicExec_dInst[143:139] != 5'd4 &&
	       basicExec_dInst[143:139] != 5'd5 &&
	       basicExec_dInst[143:139] != 5'd6 &&
	       basicExec_dInst[143:139] != 5'd7 &&
	       basicExec_dInst[143:139] != 5'd2 &&
	       brAddrCalc___d245[77],
	       basicExec_dInst[143:139] != 5'd4 &&
	       basicExec_dInst[143:139] != 5'd5 &&
	       basicExec_dInst[143:139] != 5'd6 &&
	       basicExec_dInst[143:139] != 5'd7 &&
	       basicExec_dInst[143:139] != 5'd2 &&
	       brAddrCalc___d245[76],
	       basicExec_dInst[143:139] != 5'd4 &&
	       basicExec_dInst[143:139] != 5'd5 &&
	       basicExec_dInst[143:139] != 5'd6 &&
	       basicExec_dInst[143:139] != 5'd7 &&
	       basicExec_dInst[143:139] != 5'd2 &&
	       brAddrCalc___d245[75],
	       basicExec_dInst[143:139] != 5'd4 &&
	       basicExec_dInst[143:139] != 5'd5 &&
	       basicExec_dInst[143:139] != 5'd6 &&
	       basicExec_dInst[143:139] != 5'd7 &&
	       basicExec_dInst[143:139] != 5'd2 &&
	       brAddrCalc___d245[74],
	       basicExec_dInst[143:139] != 5'd4 &&
	       basicExec_dInst[143:139] != 5'd5 &&
	       basicExec_dInst[143:139] != 5'd6 &&
	       basicExec_dInst[143:139] != 5'd7 &&
	       basicExec_dInst[143:139] != 5'd2 &&
	       brAddrCalc___d245[73],
	       basicExec_dInst[143:139] != 5'd4 &&
	       basicExec_dInst[143:139] != 5'd5 &&
	       basicExec_dInst[143:139] != 5'd6 &&
	       basicExec_dInst[143:139] != 5'd7 &&
	       basicExec_dInst[143:139] != 5'd2 &&
	       brAddrCalc___d245[72],
	       basicExec_dInst[143:139] != 5'd4 &&
	       basicExec_dInst[143:139] != 5'd5 &&
	       basicExec_dInst[143:139] != 5'd6 &&
	       basicExec_dInst[143:139] != 5'd7 &&
	       basicExec_dInst[143:139] != 5'd2 &&
	       brAddrCalc___d245[71],
	       basicExec_dInst[143:139] != 5'd4 &&
	       basicExec_dInst[143:139] != 5'd5 &&
	       basicExec_dInst[143:139] != 5'd6 &&
	       basicExec_dInst[143:139] != 5'd7 &&
	       basicExec_dInst[143:139] != 5'd2 &&
	       brAddrCalc___d245[70],
	       basicExec_dInst[143:139] != 5'd4 &&
	       basicExec_dInst[143:139] != 5'd5 &&
	       basicExec_dInst[143:139] != 5'd6 &&
	       basicExec_dInst[143:139] != 5'd7 &&
	       basicExec_dInst[143:139] != 5'd2 &&
	       brAddrCalc___d245[69],
	       basicExec_dInst[143:139] != 5'd4 &&
	       basicExec_dInst[143:139] != 5'd5 &&
	       basicExec_dInst[143:139] != 5'd6 &&
	       basicExec_dInst[143:139] != 5'd7 &&
	       basicExec_dInst[143:139] != 5'd2 &&
	       brAddrCalc___d245[68],
	       basicExec_dInst[143:139] != 5'd4 &&
	       basicExec_dInst[143:139] != 5'd5 &&
	       basicExec_dInst[143:139] != 5'd6 &&
	       basicExec_dInst[143:139] != 5'd7 &&
	       basicExec_dInst[143:139] != 5'd2 &&
	       brAddrCalc___d245[67],
	       basicExec_dInst[143:139] != 5'd4 &&
	       basicExec_dInst[143:139] != 5'd5 &&
	       basicExec_dInst[143:139] != 5'd6 &&
	       basicExec_dInst[143:139] != 5'd7 &&
	       basicExec_dInst[143:139] != 5'd2 &&
	       brAddrCalc___d245[66],
	       addr_capFat_flags__h4844,
	       IF_basicExec_dInst_BITS_143_TO_139_EQ_4_29_OR__ETC___d771,
	       addr_tempFields_repBoundTopBits__h4939,
	       basicExec_dInst[143:139] == 5'd4 ||
	       basicExec_dInst[143:139] == 5'd5 ||
	       basicExec_dInst[143:139] == 5'd6 ||
	       basicExec_dInst[143:139] == 5'd7 ||
	       basicExec_dInst[143:139] == 5'd2 ||
	       brAddrCalc___d245[6],
	       basicExec_dInst[143:139] == 5'd4 ||
	       basicExec_dInst[143:139] == 5'd5 ||
	       basicExec_dInst[143:139] == 5'd6 ||
	       basicExec_dInst[143:139] == 5'd7 ||
	       basicExec_dInst[143:139] == 5'd2 ||
	       brAddrCalc___d245[5],
	       basicExec_dInst[143:139] == 5'd4 ||
	       basicExec_dInst[143:139] == 5'd5 ||
	       basicExec_dInst[143:139] == 5'd6 ||
	       basicExec_dInst[143:139] == 5'd7 ||
	       basicExec_dInst[143:139] == 5'd2 ||
	       brAddrCalc___d245[4],
	       CASE_basicExec_dInst_BITS_143_TO_139_2_0_4_0_5_ETC__q4 } ;
  assign NOT_basicExec_dInst_BIT_32_4_5_AND_IF_basicExe_ETC___d727 =
	     { !basicExec_dInst[32] &&
	       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d248,
	       IF_basicExec_dInst_BIT_32_4_THEN_0_CONCAT_SEXT_ETC___d719,
	       basicExec_dInst[32] ?
		 3'd7 :
		 _theResult___snd_tempFields_repBoundTopBits__h3672,
	       basicExec_dInst_BIT_32_4_OR_IF_basicExec_dInst_ETC___d726 } ;
  assign NOT_basicExec_dInst_BIT_75_43_44_OR_basicExec__ETC___d852 =
	     !basicExec_dInst[75] ||
	     basicExec_rVal2[162] &&
	     basicExec_rVal2[159:96] != 64'hFFFFFFFFFFFFFFFF ||
	     ((basicExec_dInst[138:136] == 3'd1) ?
		!brAddrCalc___d245[162] :
		!basicExec_rVal1[162]) ;
  assign _0_CONCAT_basicExec_pcc_BITS_159_TO_96_60_PLUS__ETC___d274 =
	     x__h2522[13:11] < repBound__h3653 ;
  assign _theResult___snd_capFat_addrBits__h877 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[95:82] :
	       basicExec_rVal1[95:82] ;
  assign _theResult___snd_capFat_address__h876 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[161:96] :
	       basicExec_rVal1[161:96] ;
  assign _theResult___snd_capFat_flags__h879 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[65] :
	       basicExec_rVal1[65] ;
  assign _theResult___snd_capFat_otype__h881 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[62:45] :
	       basicExec_rVal1[62:45] ;
  assign _theResult___snd_capFat_perms_soft__h3135 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[81:78] :
	       basicExec_rVal1[81:78] ;
  assign _theResult___snd_capFat_reserved__h880 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[64:63] :
	       basicExec_rVal1[64:63] ;
  assign _theResult___snd_tempFields_repBoundTopBits__h3672 =
	     (basicExec_dInst[138:136] == 3'd1) ?
	       brAddrCalc___d245[9:7] :
	       basicExec_rVal1[9:7] ;
  assign addr__h4016 =
	     { {32{basicExec_dInst_BITS_31_TO_0__q1[31]}},
	       basicExec_dInst_BITS_31_TO_0__q1 } ;
  assign addr__h403 = x__h2512 | in__h2645[63:0] ;
  assign addr__h407 = (x__h2923 | in__h2959[63:0]) + addr__h4016 ;
  assign addr_capFat_flags__h4844 =
	     basicExec_dInst[143:139] != 5'd4 &&
	     basicExec_dInst[143:139] != 5'd5 &&
	     basicExec_dInst[143:139] != 5'd6 &&
	     basicExec_dInst[143:139] != 5'd7 &&
	     basicExec_dInst[143:139] != 5'd2 &&
	     brAddrCalc___d245[65] ;
  assign address__h398 =
	     basicExec_pcc[159:96] + { {52{inc__h397[11]}}, inc__h397 } ;
  assign aluVal2_capFat_addrBits__h1259 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) ?
	       basicExec_rVal2[95:82] :
	       { 2'b0, addr__h4016[63:52] } ;
  assign aluVal2_capFat_address__h1258 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) ?
	       basicExec_rVal2[161:96] :
	       { 2'd0, addr__h4016 } ;
  assign aluVal2_capFat_flags__h1261 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) &&
	     basicExec_rVal2[65] ;
  assign aluVal2_capFat_otype__h1263 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) ?
	       basicExec_rVal2[62:45] :
	       18'd262143 ;
  assign aluVal2_capFat_perms_soft__h1320 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) ?
	       basicExec_rVal2[81:78] :
	       4'd0 ;
  assign aluVal2_capFat_reserved__h1262 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) ?
	       basicExec_rVal2[64:63] :
	       2'd0 ;
  assign aluVal2_tempFields_repBoundTopBits__h1631 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) ?
	       basicExec_rVal2[9:7] :
	       3'd7 ;
  assign base__h2499 =
	     { IF_basicExec_pcc_BITS_23_TO_21_70_ULT_basicExe_ETC___d279,
	       basicExec_pcc[23:10] } ;
  assign base__h2910 = { basicExec_pcc[1:0], basicExec_pcc[23:10] } ;
  assign basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d48 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) &&
	     basicExec_rVal2[162] ;
  assign basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d61 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) &&
	     basicExec_rVal2[77] ;
  assign basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d63 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) &&
	     basicExec_rVal2[76] ;
  assign basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d65 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) &&
	     basicExec_rVal2[75] ;
  assign basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d67 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) &&
	     basicExec_rVal2[74] ;
  assign basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d69 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) &&
	     basicExec_rVal2[73] ;
  assign basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d71 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) &&
	     basicExec_rVal2[72] ;
  assign basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d73 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) &&
	     basicExec_rVal2[71] ;
  assign basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d75 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) &&
	     basicExec_rVal2[70] ;
  assign basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d77 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) &&
	     basicExec_rVal2[69] ;
  assign basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d79 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) &&
	     basicExec_rVal2[68] ;
  assign basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d81 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) &&
	     basicExec_rVal2[67] ;
  assign basicExec_dInst_BITS_108_TO_107_0_EQ_1_3_AND_N_ETC___d83 =
	     (basicExec_dInst[108:107] == 2'd1 &&
	      basicExec_dInst[106:103] != 4'd0 &&
	      basicExec_dInst[106:103] != 4'd1 &&
	      (basicExec_dInst[106:103] == 4'd2 ||
	       basicExec_dInst[106:103] != 4'd3 &&
	       basicExec_dInst[106:103] != 4'd4 &&
	       basicExec_dInst[106:103] != 4'd5 &&
	       IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 ==
	       4'd2) ||
	      !basicExec_dInst[32]) &&
	     basicExec_rVal2[66] ;
  assign basicExec_dInst_BITS_31_TO_0__q1 = basicExec_dInst[31:0] ;
  assign basicExec_dInst_BITS_97_TO_74_60_CONCAT_IF_bas_ETC___d865 =
	     { basicExec_dInst[97:74],
	       (basicExec_dInst[138:136] == 3'd1) ?
		 aluBr___d243 && basicExec_dInst[73] :
		 basicExec_dInst[73],
	       basicExec_dInst[72:52] } ;
  assign basicExec_dInst_BIT_32_4_OR_IF_basicExec_dInst_ETC___d726 =
	     { basicExec_dInst[32] ||
	       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d620,
	       basicExec_dInst[32] ||
	       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d633,
	       basicExec_dInst[32] ||
	       IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d648,
	       basicExec_dInst[32] ?
		 4'd0 :
		 IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d677 } ;
  assign basicExec_pcc_BITS_161_TO_96_02_PLUS_0_CONCAT__ETC___d645 =
	     x__h3081[13:11] < repBound__h3653 ;
  assign basicExec_pcc_BITS_23_TO_21_70_ULT_basicExec_p_ETC___d272 =
	     basicExec_pcc[23:21] < repBound__h3653 ;
  assign basicExec_pcc_BITS_37_TO_35_16_ULT_basicExec_p_ETC___d617 =
	     basicExec_pcc[37:35] < repBound__h3653 ;
  assign basicExec_pcc_CONCAT_brAddrCalc_45_BITS_162_TO_ETC___d939 =
	     { basicExec_pcc,
	       brAddrCalc___d245[162:63],
	       18'd262143,
	       brAddrCalc___d245[44:0],
	       aluBr___d243,
	       basicExec_dInst[143:139] == 5'd12 ||
	       basicExec_dInst[143:139] == 5'd11,
	       brAddrCalc___d245[162] != basicExec_ppc[162] ||
	       x__h5490 != y__h5491,
	       NOT_basicExec_dInst_BIT_75_43_44_OR_basicExec__ETC___d852 &&
	       (!basicExec_dInst[76] ||
		_theResult___snd_capFat_address__h876[63:0] != 64'd0) &&
	       capChecks___d868[11],
	       capChecks___d868[10:5],
	       CASE_capChecks_68_BITS_4_TO_0_0_capChecks_68_B_ETC__q6,
	       NOT_basicExec_dInst_BIT_75_43_44_OR_basicExec__ETC___d852 &&
	       prepareBoundsCheck___d931[265],
	       prepareBoundsCheck___d931[264:0] } ;
  assign highBitsfilter__h534 = 50'h3FFFFFFFFFFFF << basicExec_pcc[43:38] ;
  assign highOffsetBits__h535 = x__h562 & highBitsfilter__h534 ;
  assign in__h2645 = pointer__h490 & y__h2976 ;
  assign in__h2959 = basicExec_pcc[161:96] & y__h2976 ;
  assign inc__h397 = (basicExec_orig_inst[1:0] == 2'b11) ? 12'd4 : 12'd2 ;
  assign offset__h2500 = { 2'd0, x__h2522[13:0] } - base__h2499 ;
  assign offset__h2911 = { 2'd0, basicExec_pcc[95:82] } - base__h2910 ;
  assign pointer__h490 = { 2'd0, address__h398 } ;
  assign pointer__h526 = basicExec_pcc[161:96] + { 2'd0, addr__h4016 } ;
  assign repBoundBits__h541 = { basicExec_pcc[9:7], 11'd0 } ;
  assign repBound__h3653 = basicExec_pcc[23:21] - 3'b001 ;
  assign res_addrBits__h461 = { 2'b0, addr__h384[63:52] } ;
  assign res_addrBits__h505 = { 2'b0, addr__h403[63:52] } ;
  assign res_addrBits__h516 = { 2'b0, addr__h407[63:52] } ;
  assign res_addrBits__h889 = { 2'b0, alu_result__h35[63:52] } ;
  assign res_address__h460 = { 2'd0, addr__h384 } ;
  assign res_address__h504 = { 2'd0, addr__h403 } ;
  assign res_address__h515 = { 2'd0, addr__h407 } ;
  assign res_address__h888 = { 2'd0, alu_result__h35 } ;
  assign res_fst_capFat_addrBits__h480 =
	     (basicExec_dInst[108:107] == 2'd0) ?
	       res_addrBits__h461 :
	       capModify___d197[96:83] ;
  assign res_fst_capFat_address__h479 =
	     (basicExec_dInst[108:107] == 2'd0) ?
	       res_address__h460 :
	       capModify___d197[162:97] ;
  assign res_fst_capFat_flags__h482 =
	     basicExec_dInst[108:107] != 2'd0 && capModify___d197[66] ;
  assign res_fst_capFat_otype__h484 =
	     (basicExec_dInst[108:107] == 2'd0) ?
	       18'd262143 :
	       capModify___d197[63:46] ;
  assign res_fst_capFat_perms_soft__h3129 =
	     (basicExec_dInst[108:107] == 2'd0) ?
	       4'd0 :
	       capModify___d197[82:79] ;
  assign res_fst_capFat_reserved__h483 =
	     (basicExec_dInst[108:107] == 2'd0) ?
	       basicExec_dInst[108:107] :
	       capModify___d197[65:64] ;
  assign res_fst_tempFields_repBoundTopBits__h3623 =
	     (basicExec_dInst[108:107] == 2'd0) ?
	       3'd7 :
	       capModify___d197[10:8] ;
  assign result_d_address__h849 = { 2'd0, pointer__h526[63:0] } ;
  assign signBits__h532 = {50{addr__h4016[63]}} ;
  assign toBoundsM1__h545 = repBoundBits__h541 + ~basicExec_pcc[95:82] ;
  assign toBounds__h544 = repBoundBits__h541 - basicExec_pcc[95:82] ;
  assign x__h2512 = x__h2514 << basicExec_pcc[43:38] ;
  assign x__h2514 = { {48{offset__h2500[15]}}, offset__h2500 } ;
  assign x__h2522 = pointer__h490 >> basicExec_pcc[43:38] ;
  assign x__h2923 = x__h2925 << basicExec_pcc[43:38] ;
  assign x__h2925 = { {48{offset__h2911[15]}}, offset__h2911 } ;
  assign x__h2977 = 66'h3FFFFFFFFFFFFFFFF << basicExec_pcc[43:38] ;
  assign x__h3081 = pointer__h526 >> basicExec_pcc[43:38] ;
  assign x__h5490 =
	     { brAddrCalc___d245[81:66],
	       brAddrCalc___d245[64:63],
	       brAddrCalc___d245[65],
	       18'd0,
	       ~brAddrCalc___d245[44],
	       IF_brAddrCalc_45_BIT_44_71_THEN_brAddrCalc_45__ETC___d800[25:17],
	       ~IF_brAddrCalc_45_BIT_44_71_THEN_brAddrCalc_45__ETC___d800[16:15],
	       IF_brAddrCalc_45_BIT_44_71_THEN_brAddrCalc_45__ETC___d800[14:3],
	       ~IF_brAddrCalc_45_BIT_44_71_THEN_brAddrCalc_45__ETC___d800[2],
	       IF_brAddrCalc_45_BIT_44_71_THEN_brAddrCalc_45__ETC___d800[1:0],
	       brAddrCalc___d245[159:96] } ;
  assign x__h562 = addr__h4016[63:14] ^ signBits__h532 ;
  assign x__h771 = addr__h4016 >> basicExec_pcc[43:38] ;
  assign y__h2976 = ~x__h2977 ;
  assign y__h5491 =
	     { basicExec_ppc[81:66],
	       basicExec_ppc[64:63],
	       basicExec_ppc[65],
	       ~basicExec_ppc[62:44],
	       IF_basicExec_ppc_BIT_44_18_THEN_basicExec_ppc__ETC___d826[25:17],
	       ~IF_basicExec_ppc_BIT_44_18_THEN_basicExec_ppc__ETC___d826[16:15],
	       IF_basicExec_ppc_BIT_44_18_THEN_basicExec_ppc__ETC___d826[14:3],
	       ~IF_basicExec_ppc_BIT_44_18_THEN_basicExec_ppc__ETC___d826[2],
	       IF_basicExec_ppc_BIT_44_18_THEN_basicExec_ppc__ETC___d826[1:0],
	       basicExec_ppc[159:96] } ;
  always@(basicExec_dInst)
  begin
    case (basicExec_dInst[106:103])
      4'd6, 4'd7, 4'd8, 4'd9, 4'd10:
	  IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 =
	      basicExec_dInst[106:103];
      default: IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35 =
		   4'd11;
    endcase
  end
  always@(basicExec_dInst)
  begin
    case (basicExec_dInst[102:100])
      3'd2, 3'd3:
	  IF_basicExec_dInst_BITS_102_TO_100_44_EQ_2_48__ETC___d151 =
	      basicExec_dInst[102:100];
      default: IF_basicExec_dInst_BITS_102_TO_100_44_EQ_2_48__ETC___d151 =
		   3'd4;
    endcase
  end
  always@(basicExec_dInst or brAddrCalc___d245 or res_address__h888)
  begin
    case (basicExec_dInst[143:139])
      5'd2, 5'd4, 5'd5, 5'd6, 5'd7:
	  addr_capFat_address__h4841 = res_address__h888;
      default: addr_capFat_address__h4841 = brAddrCalc___d245[161:96];
    endcase
  end
  always@(basicExec_dInst or brAddrCalc___d245 or res_addrBits__h889)
  begin
    case (basicExec_dInst[143:139])
      5'd2, 5'd4, 5'd5, 5'd6, 5'd7:
	  addr_capFat_addrBits__h4842 = res_addrBits__h889;
      default: addr_capFat_addrBits__h4842 = brAddrCalc___d245[95:82];
    endcase
  end
  always@(basicExec_dInst or brAddrCalc___d245)
  begin
    case (basicExec_dInst[143:139])
      5'd2, 5'd4, 5'd5, 5'd6, 5'd7: addr_capFat_perms_soft__h4865 = 4'd0;
      default: addr_capFat_perms_soft__h4865 = brAddrCalc___d245[81:78];
    endcase
  end
  always@(basicExec_dInst or brAddrCalc___d245)
  begin
    case (basicExec_dInst[143:139])
      5'd2, 5'd4, 5'd5, 5'd6, 5'd7: addr_capFat_reserved__h4845 = 2'd0;
      default: addr_capFat_reserved__h4845 = brAddrCalc___d245[64:63];
    endcase
  end
  always@(basicExec_dInst or brAddrCalc___d245)
  begin
    case (basicExec_dInst[143:139])
      5'd2, 5'd4, 5'd5, 5'd6, 5'd7:
	  addr_tempFields_repBoundTopBits__h4939 = 3'd7;
      default: addr_tempFields_repBoundTopBits__h4939 =
		   brAddrCalc___d245[9:7];
    endcase
  end
  always@(IF_basicExec_dInst_BITS_102_TO_100_44_EQ_2_48__ETC___d151)
  begin
    case (IF_basicExec_dInst_BITS_102_TO_100_44_EQ_2_48__ETC___d151)
      3'd2, 3'd3:
	  CASE_IF_basicExec_dInst_BITS_102_TO_100_44_EQ__ETC__q2 =
	      IF_basicExec_dInst_BITS_102_TO_100_44_EQ_2_48__ETC___d151;
      default: CASE_IF_basicExec_dInst_BITS_102_TO_100_44_EQ__ETC__q2 = 3'd4;
    endcase
  end
  always@(basicExec_dInst or brAddrCalc___d245)
  begin
    case (basicExec_dInst[143:139])
      5'd2, 5'd4, 5'd5, 5'd6, 5'd7:
	  CASE_basicExec_dInst_BITS_143_TO_139_2_1402575_ETC__q3 =
	      34'h344000000;
      default: CASE_basicExec_dInst_BITS_143_TO_139_2_1402575_ETC__q3 =
		   brAddrCalc___d245[43:10];
    endcase
  end
  always@(basicExec_dInst or brAddrCalc___d245)
  begin
    case (basicExec_dInst[143:139])
      5'd2, 5'd4, 5'd5, 5'd6, 5'd7:
	  CASE_basicExec_dInst_BITS_143_TO_139_2_0_4_0_5_ETC__q4 = 4'd0;
      default: CASE_basicExec_dInst_BITS_143_TO_139_2_0_4_0_5_ETC__q4 =
		   brAddrCalc___d245[3:0];
    endcase
  end
  always@(IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35)
  begin
    case (IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35)
      4'd6, 4'd7, 4'd8, 4'd9, 4'd10:
	  CASE_IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_ETC__q5 =
	      IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_6_OR_ETC___d35;
      default: CASE_IF_basicExec_dInst_BITS_106_TO_103_4_EQ_6_ETC__q5 = 4'd11;
    endcase
  end
  always@(basicExec_dInst or
	  capModify___d197 or
	  highOffsetBits__h535 or
	  IF_SEXT_basicExec_dInst_BITS_31_TO_0_0_1_BIT_6_ETC___d229 or
	  basicExec_pcc or
	  IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d248)
  begin
    case (basicExec_dInst[143:139])
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d254 =
	      (highOffsetBits__h535 == 50'd0 &&
	       IF_SEXT_basicExec_dInst_BITS_31_TO_0_0_1_BIT_6_ETC___d229 ||
	       basicExec_pcc[43:38] >= 6'd50) &&
	      basicExec_pcc[162];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d254 =
	      IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d248;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d254 =
		   (basicExec_dInst[143:139] == 5'd18 ||
		    basicExec_dInst[143:139] == 5'd13) &&
		   basicExec_dInst[108:107] != 2'd0 &&
		   capModify___d197[163];
    endcase
  end
  always@(basicExec_dInst or
	  capModify___d197 or
	  basicExec_pcc or
	  IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d371)
  begin
    case (basicExec_dInst[143:139])
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d374 =
	      basicExec_pcc[77];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d374 =
	      IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d371;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d374 =
		   (basicExec_dInst[143:139] == 5'd18 ||
		    basicExec_dInst[143:139] == 5'd13) &&
		   basicExec_dInst[108:107] != 2'd0 &&
		   capModify___d197[78];
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d374 or
	  capModify___d197 or basicExec_pcc)
  begin
    case (basicExec_dInst[143:139])
      5'd11:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d377 =
	      basicExec_dInst[108:107] != 2'd0 && capModify___d197[78];
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d377 =
	      basicExec_pcc[77];
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d377 =
		   basicExec_dInst[143:139] != 5'd9 &&
		   basicExec_dInst[143:139] != 5'd14 &&
		   IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d374;
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d254 or
	  capModify___d197 or basicExec_pcc)
  begin
    case (basicExec_dInst[143:139])
      5'd11:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d258 =
	      basicExec_dInst[108:107] != 2'd0 && capModify___d197[163];
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d258 =
	      basicExec_pcc[162];
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d258 =
		   basicExec_dInst[143:139] != 5'd9 &&
		   basicExec_dInst[143:139] != 5'd14 &&
		   IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d254;
    endcase
  end
  always@(basicExec_dInst or
	  capModify___d197 or
	  basicExec_pcc or
	  IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d384)
  begin
    case (basicExec_dInst[143:139])
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d387 =
	      basicExec_pcc[76];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d387 =
	      IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d384;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d387 =
		   (basicExec_dInst[143:139] == 5'd18 ||
		    basicExec_dInst[143:139] == 5'd13) &&
		   basicExec_dInst[108:107] != 2'd0 &&
		   capModify___d197[77];
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d387 or
	  capModify___d197 or basicExec_pcc)
  begin
    case (basicExec_dInst[143:139])
      5'd11:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d390 =
	      basicExec_dInst[108:107] != 2'd0 && capModify___d197[77];
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d390 =
	      basicExec_pcc[76];
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d390 =
		   basicExec_dInst[143:139] != 5'd9 &&
		   basicExec_dInst[143:139] != 5'd14 &&
		   IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d387;
    endcase
  end
  always@(basicExec_dInst or
	  capModify___d197 or
	  basicExec_pcc or
	  IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d397)
  begin
    case (basicExec_dInst[143:139])
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d400 =
	      basicExec_pcc[75];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d400 =
	      IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d397;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d400 =
		   (basicExec_dInst[143:139] == 5'd18 ||
		    basicExec_dInst[143:139] == 5'd13) &&
		   basicExec_dInst[108:107] != 2'd0 &&
		   capModify___d197[76];
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d400 or
	  capModify___d197 or basicExec_pcc)
  begin
    case (basicExec_dInst[143:139])
      5'd11:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d403 =
	      basicExec_dInst[108:107] != 2'd0 && capModify___d197[76];
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d403 =
	      basicExec_pcc[75];
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d403 =
		   basicExec_dInst[143:139] != 5'd9 &&
		   basicExec_dInst[143:139] != 5'd14 &&
		   IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d400;
    endcase
  end
  always@(basicExec_dInst or
	  capModify___d197 or
	  basicExec_pcc or
	  IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d410)
  begin
    case (basicExec_dInst[143:139])
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d413 =
	      basicExec_pcc[74];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d413 =
	      IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d410;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d413 =
		   (basicExec_dInst[143:139] == 5'd18 ||
		    basicExec_dInst[143:139] == 5'd13) &&
		   basicExec_dInst[108:107] != 2'd0 &&
		   capModify___d197[75];
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d413 or
	  capModify___d197 or basicExec_pcc)
  begin
    case (basicExec_dInst[143:139])
      5'd11:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d416 =
	      basicExec_dInst[108:107] != 2'd0 && capModify___d197[75];
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d416 =
	      basicExec_pcc[74];
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d416 =
		   basicExec_dInst[143:139] != 5'd9 &&
		   basicExec_dInst[143:139] != 5'd14 &&
		   IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d413;
    endcase
  end
  always@(basicExec_dInst or
	  capModify___d197 or
	  basicExec_pcc or
	  IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d423)
  begin
    case (basicExec_dInst[143:139])
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d426 =
	      basicExec_pcc[73];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d426 =
	      IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d423;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d426 =
		   (basicExec_dInst[143:139] == 5'd18 ||
		    basicExec_dInst[143:139] == 5'd13) &&
		   basicExec_dInst[108:107] != 2'd0 &&
		   capModify___d197[74];
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d426 or
	  capModify___d197 or basicExec_pcc)
  begin
    case (basicExec_dInst[143:139])
      5'd11:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d429 =
	      basicExec_dInst[108:107] != 2'd0 && capModify___d197[74];
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d429 =
	      basicExec_pcc[73];
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d429 =
		   basicExec_dInst[143:139] != 5'd9 &&
		   basicExec_dInst[143:139] != 5'd14 &&
		   IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d426;
    endcase
  end
  always@(basicExec_dInst or
	  capModify___d197 or
	  basicExec_pcc or
	  IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d436)
  begin
    case (basicExec_dInst[143:139])
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d439 =
	      basicExec_pcc[72];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d439 =
	      IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d436;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d439 =
		   (basicExec_dInst[143:139] == 5'd18 ||
		    basicExec_dInst[143:139] == 5'd13) &&
		   basicExec_dInst[108:107] != 2'd0 &&
		   capModify___d197[73];
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d439 or
	  capModify___d197 or basicExec_pcc)
  begin
    case (basicExec_dInst[143:139])
      5'd11:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d442 =
	      basicExec_dInst[108:107] != 2'd0 && capModify___d197[73];
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d442 =
	      basicExec_pcc[72];
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d442 =
		   basicExec_dInst[143:139] != 5'd9 &&
		   basicExec_dInst[143:139] != 5'd14 &&
		   IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d439;
    endcase
  end
  always@(basicExec_dInst or
	  capModify___d197 or
	  basicExec_pcc or
	  IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d449)
  begin
    case (basicExec_dInst[143:139])
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d452 =
	      basicExec_pcc[71];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d452 =
	      IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d449;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d452 =
		   (basicExec_dInst[143:139] == 5'd18 ||
		    basicExec_dInst[143:139] == 5'd13) &&
		   basicExec_dInst[108:107] != 2'd0 &&
		   capModify___d197[72];
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d452 or
	  capModify___d197 or basicExec_pcc)
  begin
    case (basicExec_dInst[143:139])
      5'd11:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d455 =
	      basicExec_dInst[108:107] != 2'd0 && capModify___d197[72];
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d455 =
	      basicExec_pcc[71];
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d455 =
		   basicExec_dInst[143:139] != 5'd9 &&
		   basicExec_dInst[143:139] != 5'd14 &&
		   IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d452;
    endcase
  end
  always@(basicExec_dInst or
	  capModify___d197 or
	  basicExec_pcc or
	  IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d462)
  begin
    case (basicExec_dInst[143:139])
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d465 =
	      basicExec_pcc[70];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d465 =
	      IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d462;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d465 =
		   (basicExec_dInst[143:139] == 5'd18 ||
		    basicExec_dInst[143:139] == 5'd13) &&
		   basicExec_dInst[108:107] != 2'd0 &&
		   capModify___d197[71];
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d465 or
	  capModify___d197 or basicExec_pcc)
  begin
    case (basicExec_dInst[143:139])
      5'd11:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d468 =
	      basicExec_dInst[108:107] != 2'd0 && capModify___d197[71];
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d468 =
	      basicExec_pcc[70];
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d468 =
		   basicExec_dInst[143:139] != 5'd9 &&
		   basicExec_dInst[143:139] != 5'd14 &&
		   IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d465;
    endcase
  end
  always@(basicExec_dInst or
	  capModify___d197 or
	  basicExec_pcc or
	  IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d475)
  begin
    case (basicExec_dInst[143:139])
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d478 =
	      basicExec_pcc[69];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d478 =
	      IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d475;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d478 =
		   (basicExec_dInst[143:139] == 5'd18 ||
		    basicExec_dInst[143:139] == 5'd13) &&
		   basicExec_dInst[108:107] != 2'd0 &&
		   capModify___d197[70];
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d478 or
	  capModify___d197 or basicExec_pcc)
  begin
    case (basicExec_dInst[143:139])
      5'd11:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d481 =
	      basicExec_dInst[108:107] != 2'd0 && capModify___d197[70];
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d481 =
	      basicExec_pcc[69];
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d481 =
		   basicExec_dInst[143:139] != 5'd9 &&
		   basicExec_dInst[143:139] != 5'd14 &&
		   IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d478;
    endcase
  end
  always@(basicExec_dInst or
	  capModify___d197 or
	  basicExec_pcc or
	  IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d488)
  begin
    case (basicExec_dInst[143:139])
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d491 =
	      basicExec_pcc[68];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d491 =
	      IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d488;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d491 =
		   (basicExec_dInst[143:139] == 5'd18 ||
		    basicExec_dInst[143:139] == 5'd13) &&
		   basicExec_dInst[108:107] != 2'd0 &&
		   capModify___d197[69];
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d491 or
	  capModify___d197 or basicExec_pcc)
  begin
    case (basicExec_dInst[143:139])
      5'd11:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d494 =
	      basicExec_dInst[108:107] != 2'd0 && capModify___d197[69];
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d494 =
	      basicExec_pcc[68];
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d494 =
		   basicExec_dInst[143:139] != 5'd9 &&
		   basicExec_dInst[143:139] != 5'd14 &&
		   IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d491;
    endcase
  end
  always@(basicExec_dInst or
	  capModify___d197 or
	  basicExec_pcc or
	  IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d501)
  begin
    case (basicExec_dInst[143:139])
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d504 =
	      basicExec_pcc[67];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d504 =
	      IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d501;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d504 =
		   (basicExec_dInst[143:139] == 5'd18 ||
		    basicExec_dInst[143:139] == 5'd13) &&
		   basicExec_dInst[108:107] != 2'd0 &&
		   capModify___d197[68];
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d504 or
	  capModify___d197 or basicExec_pcc)
  begin
    case (basicExec_dInst[143:139])
      5'd11:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d507 =
	      basicExec_dInst[108:107] != 2'd0 && capModify___d197[68];
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d507 =
	      basicExec_pcc[67];
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d507 =
		   basicExec_dInst[143:139] != 5'd9 &&
		   basicExec_dInst[143:139] != 5'd14 &&
		   IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d504;
    endcase
  end
  always@(basicExec_dInst or
	  capModify___d197 or
	  basicExec_pcc or
	  IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d514)
  begin
    case (basicExec_dInst[143:139])
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d517 =
	      basicExec_pcc[66];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d517 =
	      IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d514;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d517 =
		   (basicExec_dInst[143:139] == 5'd18 ||
		    basicExec_dInst[143:139] == 5'd13) &&
		   basicExec_dInst[108:107] != 2'd0 &&
		   capModify___d197[67];
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d517 or
	  capModify___d197 or basicExec_pcc)
  begin
    case (basicExec_dInst[143:139])
      5'd11:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d520 =
	      basicExec_dInst[108:107] != 2'd0 && capModify___d197[67];
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d520 =
	      basicExec_pcc[66];
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d520 =
		   basicExec_dInst[143:139] != 5'd9 &&
		   basicExec_dInst[143:139] != 5'd14 &&
		   IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d517;
    endcase
  end
  always@(basicExec_dInst or
	  res_fst_capFat_flags__h482 or
	  basicExec_pcc or _theResult___snd_capFat_flags__h879)
  begin
    case (basicExec_dInst[143:139])
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d536 =
	      basicExec_pcc[65];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d536 =
	      _theResult___snd_capFat_flags__h879;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d536 =
		   (basicExec_dInst[143:139] == 5'd18 ||
		    basicExec_dInst[143:139] == 5'd13) &&
		   res_fst_capFat_flags__h482;
    endcase
  end
  always@(basicExec_dInst or
	  capModify___d197 or
	  basicExec_pcc or
	  IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d573)
  begin
    case (basicExec_dInst[143:139])
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d579 =
	      basicExec_pcc[44];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d579 =
	      IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d573;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d579 =
		   basicExec_dInst[143:139] != 5'd18 &&
		   basicExec_dInst[143:139] != 5'd13 ||
		   basicExec_dInst[108:107] == 2'd0 ||
		   capModify___d197[45];
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d579 or
	  capModify___d197 or basicExec_pcc)
  begin
    case (basicExec_dInst[143:139])
      5'd11:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d583 =
	      basicExec_dInst[108:107] == 2'd0 || capModify___d197[45];
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d583 =
	      basicExec_pcc[44];
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d583 =
		   basicExec_dInst[143:139] == 5'd9 ||
		   basicExec_dInst[143:139] == 5'd14 ||
		   IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d579;
    endcase
  end
  always@(basicExec_dInst or
	  res_fst_capFat_reserved__h483 or
	  basicExec_pcc or _theResult___snd_capFat_reserved__h880)
  begin
    case (basicExec_dInst[143:139])
      5'd8, 5'd9, 5'd14:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d554 = 2'd0;
      5'd11, 5'd13, 5'd18:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d554 =
	      res_fst_capFat_reserved__h483;
      5'd12, 5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d554 =
	      basicExec_pcc[64:63];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d554 =
	      _theResult___snd_capFat_reserved__h880;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d554 =
		   2'd0;
    endcase
  end
  always@(basicExec_dInst or
	  res_fst_capFat_perms_soft__h3129 or
	  basicExec_pcc or _theResult___snd_capFat_perms_soft__h3135)
  begin
    case (basicExec_dInst[143:139])
      5'd8, 5'd9, 5'd14:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d364 = 4'd0;
      5'd11, 5'd13, 5'd18:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d364 =
	      res_fst_capFat_perms_soft__h3129;
      5'd12, 5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d364 =
	      basicExec_pcc[81:78];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d364 =
	      _theResult___snd_capFat_perms_soft__h3135;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d364 =
		   4'd0;
    endcase
  end
  always@(basicExec_dInst or
	  res_address__h888 or
	  res_address__h504 or
	  res_fst_capFat_address__h479 or
	  pointer__h490 or
	  res_address__h515 or
	  result_d_address__h849 or _theResult___snd_capFat_address__h876)
  begin
    case (basicExec_dInst[143:139])
      5'd8, 5'd9:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d327 =
	      res_address__h504;
      5'd11, 5'd13, 5'd18:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d327 =
	      res_fst_capFat_address__h479;
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d327 =
	      pointer__h490;
      5'd14:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d327 =
	      res_address__h515;
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d327 =
	      result_d_address__h849;
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d327 =
	      _theResult___snd_capFat_address__h876;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d327 =
		   res_address__h888;
    endcase
  end
  always@(basicExec_dInst or
	  capModify___d197 or
	  basicExec_pcc_BITS_37_TO_35_16_ULT_basicExec_p_ETC___d617 or
	  IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d620)
  begin
    case (basicExec_dInst[143:139])
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d623 =
	      basicExec_pcc_BITS_37_TO_35_16_ULT_basicExec_p_ETC___d617;
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d623 =
	      IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d620;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d623 =
		   basicExec_dInst[143:139] != 5'd18 &&
		   basicExec_dInst[143:139] != 5'd13 ||
		   basicExec_dInst[108:107] == 2'd0 ||
		   capModify___d197[7];
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d623 or
	  capModify___d197 or
	  basicExec_pcc_BITS_37_TO_35_16_ULT_basicExec_p_ETC___d617)
  begin
    case (basicExec_dInst[143:139])
      5'd11:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d627 =
	      basicExec_dInst[108:107] == 2'd0 || capModify___d197[7];
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d627 =
	      basicExec_pcc_BITS_37_TO_35_16_ULT_basicExec_p_ETC___d617;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d627 =
		   basicExec_dInst[143:139] == 5'd9 ||
		   basicExec_dInst[143:139] == 5'd14 ||
		   IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d623;
    endcase
  end
  always@(basicExec_dInst or
	  capModify___d197 or
	  basicExec_pcc_BITS_23_TO_21_70_ULT_basicExec_p_ETC___d272 or
	  IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d633)
  begin
    case (basicExec_dInst[143:139])
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d636 =
	      basicExec_pcc_BITS_23_TO_21_70_ULT_basicExec_p_ETC___d272;
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d636 =
	      IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d633;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d636 =
		   basicExec_dInst[143:139] != 5'd18 &&
		   basicExec_dInst[143:139] != 5'd13 ||
		   basicExec_dInst[108:107] == 2'd0 ||
		   capModify___d197[6];
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d636 or
	  capModify___d197 or
	  basicExec_pcc_BITS_23_TO_21_70_ULT_basicExec_p_ETC___d272)
  begin
    case (basicExec_dInst[143:139])
      5'd11:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d640 =
	      basicExec_dInst[108:107] == 2'd0 || capModify___d197[6];
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d640 =
	      basicExec_pcc_BITS_23_TO_21_70_ULT_basicExec_p_ETC___d272;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d640 =
		   basicExec_dInst[143:139] == 5'd9 ||
		   basicExec_dInst[143:139] == 5'd14 ||
		   IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d636;
    endcase
  end
  always@(basicExec_dInst or
	  capModify___d197 or
	  basicExec_pcc_BITS_161_TO_96_02_PLUS_0_CONCAT__ETC___d645 or
	  IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d648)
  begin
    case (basicExec_dInst[143:139])
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d651 =
	      basicExec_pcc_BITS_161_TO_96_02_PLUS_0_CONCAT__ETC___d645;
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d651 =
	      IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d648;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d651 =
		   basicExec_dInst[143:139] != 5'd18 &&
		   basicExec_dInst[143:139] != 5'd13 ||
		   basicExec_dInst[108:107] == 2'd0 ||
		   capModify___d197[5];
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d651 or
	  capModify___d197 or
	  _0_CONCAT_basicExec_pcc_BITS_159_TO_96_60_PLUS__ETC___d274)
  begin
    case (basicExec_dInst[143:139])
      5'd11:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d655 =
	      basicExec_dInst[108:107] == 2'd0 || capModify___d197[5];
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d655 =
	      _0_CONCAT_basicExec_pcc_BITS_159_TO_96_60_PLUS__ETC___d274;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d655 =
		   basicExec_dInst[143:139] == 5'd9 ||
		   basicExec_dInst[143:139] == 5'd14 ||
		   IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d651;
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_108_TO_107_0_EQ_0_1_TH_ETC___d659 or
	  IF_basicExec_pcc_BITS_37_TO_35_16_ULT_basicExe_ETC___d664 or
	  IF_basicExec_pcc_BITS_37_TO_35_16_ULT_basicExe_ETC___d674 or
	  IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d677)
  begin
    case (basicExec_dInst[143:139])
      5'd8, 5'd9, 5'd14:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d684 = 4'd0;
      5'd11, 5'd13, 5'd18:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d684 =
	      IF_basicExec_dInst_BITS_108_TO_107_0_EQ_0_1_TH_ETC___d659;
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d684 =
	      IF_basicExec_pcc_BITS_37_TO_35_16_ULT_basicExe_ETC___d664;
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d684 =
	      IF_basicExec_pcc_BITS_37_TO_35_16_ULT_basicExe_ETC___d674;
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d684 =
	      IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d677;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d684 =
		   4'd0;
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_108_TO_107_0_EQ_0_1_TH_ETC___d586 or
	  basicExec_pcc or
	  IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d590)
  begin
    case (basicExec_dInst[143:139])
      5'd8, 5'd9, 5'd14:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_1_ETC___d597 =
	      34'h344000000;
      5'd11, 5'd13, 5'd18:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_1_ETC___d597 =
	      IF_basicExec_dInst_BITS_108_TO_107_0_EQ_0_1_TH_ETC___d586;
      5'd12, 5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_1_ETC___d597 =
	      basicExec_pcc[43:10];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_1_ETC___d597 =
	      IF_basicExec_dInst_BITS_138_TO_136_36_EQ_1_37__ETC___d590;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_1_ETC___d597 =
		   34'h344000000;
    endcase
  end
  always@(basicExec_dInst or
	  res_fst_capFat_otype__h484 or
	  basicExec_pcc or _theResult___snd_capFat_otype__h881)
  begin
    case (basicExec_dInst[143:139])
      5'd8, 5'd9, 5'd14:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_2_ETC___d567 =
	      18'd262143;
      5'd11, 5'd13, 5'd18:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_2_ETC___d567 =
	      res_fst_capFat_otype__h484;
      5'd12, 5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_2_ETC___d567 =
	      basicExec_pcc[62:45];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_2_ETC___d567 =
	      _theResult___snd_capFat_otype__h881;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_2_ETC___d567 =
		   18'd262143;
    endcase
  end
  always@(basicExec_dInst or
	  res_addrBits__h889 or
	  res_addrBits__h505 or
	  res_fst_capFat_addrBits__h480 or
	  x__h2522 or
	  res_addrBits__h516 or
	  x__h3081 or _theResult___snd_capFat_addrBits__h877)
  begin
    case (basicExec_dInst[143:139])
      5'd8, 5'd9:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d350 =
	      res_addrBits__h505;
      5'd11, 5'd13, 5'd18:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d350 =
	      res_fst_capFat_addrBits__h480;
      5'd12:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d350 =
	      x__h2522[13:0];
      5'd14:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d350 =
	      res_addrBits__h516;
      5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d350 =
	      x__h3081[13:0];
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d350 =
	      _theResult___snd_capFat_addrBits__h877;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d350 =
		   res_addrBits__h889;
    endcase
  end
  always@(basicExec_dInst or
	  res_fst_tempFields_repBoundTopBits__h3623 or
	  repBound__h3653 or
	  _theResult___snd_tempFields_repBoundTopBits__h3672)
  begin
    case (basicExec_dInst[143:139])
      5'd8, 5'd9, 5'd14:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_7_ETC___d613 = 3'd7;
      5'd11, 5'd13, 5'd18:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_7_ETC___d613 =
	      res_fst_tempFields_repBoundTopBits__h3623;
      5'd12, 5'd15:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_7_ETC___d613 =
	      repBound__h3653;
      5'd17:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_7_ETC___d613 =
	      _theResult___snd_tempFields_repBoundTopBits__h3672;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_7_ETC___d613 =
		   3'd7;
    endcase
  end
  always@(capChecks___d868)
  begin
    case (capChecks___d868[4:0])
      5'd0,
      5'd1,
      5'd2,
      5'd3,
      5'd4,
      5'd5,
      5'd6,
      5'd7,
      5'd8,
      5'd9,
      5'd10,
      5'd11,
      5'd16,
      5'd17,
      5'd18,
      5'd19,
      5'd20,
      5'd21,
      5'd22,
      5'd23,
      5'd24,
      5'd25,
      5'd26:
	  CASE_capChecks_68_BITS_4_TO_0_0_capChecks_68_B_ETC__q6 =
	      capChecks___d868[4:0];
      default: CASE_capChecks_68_BITS_4_TO_0_0_capChecks_68_B_ETC__q6 = 5'd27;
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d536 or
	  res_fst_capFat_flags__h482 or basicExec_pcc)
  begin
    case (basicExec_dInst[143:139])
      5'd11:
	  CASE_basicExec_dInst_BITS_143_TO_139_11_res_fs_ETC__q7 =
	      res_fst_capFat_flags__h482;
      5'd12:
	  CASE_basicExec_dInst_BITS_143_TO_139_11_res_fs_ETC__q7 =
	      basicExec_pcc[65];
      default: CASE_basicExec_dInst_BITS_143_TO_139_11_res_fs_ETC__q7 =
		   basicExec_dInst[143:139] != 5'd9 &&
		   basicExec_dInst[143:139] != 5'd14 &&
		   IF_basicExec_dInst_BITS_143_TO_139_EQ_15_06_TH_ETC___d536;
    endcase
  end
  always@(basicExec_dInst or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d258 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d327 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d350 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d364 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d377 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d390 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d403 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d416 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d429 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d442 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d455 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d468 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d481 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d494 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d507 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d520 or
	  CASE_basicExec_dInst_BITS_143_TO_139_11_res_fs_ETC__q7 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d554 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_2_ETC___d567 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d583 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_1_ETC___d597 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_7_ETC___d613 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d627 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d640 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d655 or
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d684 or
	  basicExec_rVal2)
  begin
    case (basicExec_dInst[143:139])
      5'd2, 5'd5, 5'd7:
	  IF_basicExec_dInst_BITS_143_TO_139_EQ_5_OR_bas_ETC___d688 =
	      basicExec_rVal2;
      default: IF_basicExec_dInst_BITS_143_TO_139_EQ_5_OR_bas_ETC___d688 =
		   { basicExec_dInst[143:139] != 5'd8 &&
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d258,
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d327,
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d350,
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d364,
		     basicExec_dInst[143:139] != 5'd8 &&
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d377,
		     basicExec_dInst[143:139] != 5'd8 &&
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d390,
		     basicExec_dInst[143:139] != 5'd8 &&
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d403,
		     basicExec_dInst[143:139] != 5'd8 &&
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d416,
		     basicExec_dInst[143:139] != 5'd8 &&
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d429,
		     basicExec_dInst[143:139] != 5'd8 &&
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d442,
		     basicExec_dInst[143:139] != 5'd8 &&
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d455,
		     basicExec_dInst[143:139] != 5'd8 &&
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d468,
		     basicExec_dInst[143:139] != 5'd8 &&
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d481,
		     basicExec_dInst[143:139] != 5'd8 &&
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d494,
		     basicExec_dInst[143:139] != 5'd8 &&
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d507,
		     basicExec_dInst[143:139] != 5'd8 &&
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d520,
		     basicExec_dInst[143:139] != 5'd8 &&
		     CASE_basicExec_dInst_BITS_143_TO_139_11_res_fs_ETC__q7,
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d554,
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_2_ETC___d567,
		     basicExec_dInst[143:139] == 5'd8 ||
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d583,
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_1_ETC___d597,
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_7_ETC___d613,
		     basicExec_dInst[143:139] == 5'd8 ||
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d627,
		     basicExec_dInst[143:139] == 5'd8 ||
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d640,
		     basicExec_dInst[143:139] == 5'd8 ||
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_11_THEN__ETC___d655,
		     IF_basicExec_dInst_BITS_143_TO_139_EQ_8_THEN_0_ETC___d684 };
    endcase
  end
endmodule  // module_basicExec

