//
// Generated by Bluespec Compiler (build 0fccbb13)
//
// On Tue Aug 31 13:07:20 EDT 2021
//
//
// Ports:
// Name                         I/O  size props
// decode                         O   100
// decode_inst                    I    32
//
// Combinational paths from inputs to outputs:
//   decode_inst -> decode
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_decode(decode_inst,
		     decode);
  // value method decode
  input  [31 : 0] decode_inst;
  output [99 : 0] decode;

  // signals for module outputs
  wire [99 : 0] decode;

  // remaining internal signals
  reg [31 : 0] IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d603;
  reg [7 : 0] CASE_decode_inst_BITS_6_TO_0_3_decode_inst_BIT_ETC__q17;
  reg [4 : 0] CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q6,
	      CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q8,
	      CASE_decode_inst_BITS_14_TO_12_0b0_1_0b1_10_14__q9,
	      CASE_decode_inst_BITS_14_TO_12_0b0_1_0b1_10_IF_ETC__q7,
	      CASE_decode_inst_BITS_14_TO_12_0b0_21_0b1_20_19__q24,
	      CASE_decode_inst_BITS_14_TO_12_0b0_5_0b1_6_7__q23,
	      CASE_decode_inst_BITS_14_TO_12_0b1_15_0b10_16__ETC__q5,
	      CASE_decode_inst_BITS_24_TO_20_0_11_1_12_2_13_14__q25,
	      CASE_decode_inst_BITS_24_TO_20_0_15_1_16_2_17_18__q22,
	      CASE_decode_inst_BITS_31_TO_27_0b0_decode_inst_ETC__q26,
	      CASE_decode_inst_BITS_31_TO_27_0b1000_decode_i_ETC__q34,
	      CASE_decode_inst_BITS_31_TO_27_0b1000_decode_i_ETC__q40,
	      CASE_decode_inst_BITS_31_TO_27_0b10100_decode__ETC__q1,
	      CASE_decode_inst_BITS_31_TO_27_0b10_6_0b11_7_2__q31,
	      CASE_decode_inst_BITS_6_TO_0_35_decode_inst_BI_ETC__q37,
	      CASE_decode_inst_BITS_6_TO_0_3_decode_inst_BIT_ETC__q33,
	      CASE_decode_inst_BITS_6_TO_0_67_25_71_26_75_27_ETC__q27,
	      CASE_immI2_BITS_11_TO_0_0x0_17_0x1_18_0x102_19_ETC__q32,
	      IF_decode_inst_BITS_14_TO_12_1_EQ_0b1_2_THEN_1_ETC___d53,
	      IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d85,
	      IF_decode_inst_BITS_6_TO_0_EQ_19_THEN_IF_decod_ETC___d207,
	      x__h16500;
  reg [3 : 0] CASE_decode_inst_BITS_31_TO_27_0b0_1_0b1_0_0b1_ETC__q4,
	      CASE_decode_inst_BITS_31_TO_27_0b10_IF_decode__ETC__q13,
	      CASE_decode_inst_BITS_6_TO_0_3_9_7_9_35_9_39_9_ETC__q14;
  reg [2 : 0] CASE_decode_inst_BITS_14_TO_12_0b0_decode_inst_ETC__q29,
	      CASE_decode_inst_BITS_31_TO_27_0b0_4_0b1_4_0b1_ETC__q3,
	      CASE_decode_inst_BITS_31_TO_27_0b0_IF_decode_i_ETC__q10,
	      CASE_decode_inst_BITS_31_TO_27_0b10_IF_decode__ETC__q11,
	      CASE_decode_inst_BITS_6_TO_0_103_6_111_6_CASE__ETC__q30,
	      CASE_decode_inst_BITS_6_TO_0_3_0_7_0_35_IF_dec_ETC__q12,
	      IF_decode_inst_BITS_14_TO_12_1_EQ_0b1_2_THEN_5_ETC___d141,
	      IF_decode_inst_BITS_31_TO_25_5_EQ_0b0_8_OR_dec_ETC___d93,
	      IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d160,
	      IF_decode_inst_BITS_6_TO_0_EQ_35_6_OR_decode_i_ETC___d263;
  reg [1 : 0] CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_0_0b1_ETC__q21,
	      CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_1_0b1_ETC__q20,
	      IF_decode_inst_BITS_6_TO_0_EQ_3_5_OR_decode_in_ETC___d372;
  reg CASE_decode_inst_BITS_31_TO_27_0b10_NOT_decode_ETC__q41,
      CASE_decode_inst_BITS_31_TO_27_0b10_decode_ins_ETC__q15,
      CASE_decode_inst_BITS_31_TO_27_0b10_decode_ins_ETC__q18,
      CASE_decode_inst_BITS_6_TO_0_3_NOT_decode_inst_ETC__q42,
      CASE_decode_inst_BITS_6_TO_0_3_decode_inst_BIT_ETC__q16,
      CASE_decode_inst_BITS_6_TO_0_3_decode_inst_BIT_ETC__q19,
      CASE_decode_inst_BITS_6_TO_0_47_NOT_decode_ins_ETC__q36,
      CASE_decode_inst_BITS_6_TO_0_51_decode_inst_BI_ETC__q28,
      CASE_decode_inst_BITS_6_TO_0_67_NOT_decode_ins_ETC__q38,
      CASE_decode_inst_BITS_6_TO_0_67_decode_inst_BI_ETC__q35,
      CASE_decode_inst_BITS_6_TO_0_67_decode_inst_BI_ETC__q39,
      IF_decode_inst_BITS_6_TO_0_EQ_7_1_OR_decode_in_ETC___d234;
  wire [31 : 0] immB__h34, immI__h32, immJ__h36, immS__h33, immU__h35;
  wire [20 : 0] x__h15713;
  wire [17 : 0] IF_NOT_decode_inst_BITS_6_TO_0_EQ_51_09_AND_NO_ETC___d449,
		IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d451,
		IF_decode_inst_BITS_6_TO_0_EQ_3_5_THEN_IF_NOT__ETC___d374;
  wire [12 : 0] x__h15801;
  wire [11 : 0] decode_inst_BITS_31_TO_20__q2, x__h15888;
  wire [4 : 0] IF_NOT_decode_inst_BITS_26_TO_25_4_EQ_0b0_5_6__ETC___d30,
	       IF_decode_inst_BITS_14_TO_12_1_EQ_0b101_00_THE_ETC___d171;
  wire [3 : 0] IF_decode_inst_BITS_6_TO_0_EQ_47_7_THEN_IF_dec_ETC___d308;
  wire [2 : 0] IF_NOT_decode_inst_BITS_26_TO_25_4_EQ_0b0_5_6__ETC___d137,
	       IF_decode_inst_BITS_14_TO_12_1_EQ_0b0_3_OR_dec_ETC___d116;
  wire decode_inst_BIT_23_4_OR_decode_inst_BIT_21_5___d46,
       decode_inst_BIT_26_7_OR_decode_inst_BIT_24_8___d49;

  // value method decode
  assign decode =
	     { IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d85,
	       IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d160,
	       IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d451,
	       decode_inst[6:0] == 7'd115 && decode_inst[14:12] != 3'b0,
	       (immI__h32[11:0] == 12'h001 || immI__h32[11:0] == 12'd2 ||
		immI__h32[11:0] == 12'd3 ||
		immI__h32[11:0] == 12'd3072 ||
		immI__h32[11:0] == 12'd3073 ||
		immI__h32[11:0] == 12'd3074 ||
		immI__h32[11:0] == 12'd2048 ||
		immI__h32[11:0] == 12'd2049 ||
		immI__h32[11:0] == 12'd256 ||
		immI__h32[11:0] == 12'd260 ||
		immI__h32[11:0] == 12'h105 ||
		immI__h32[11:0] == 12'd262 ||
		immI__h32[11:0] == 12'd800 ||
		immI__h32[11:0] == 12'd320 ||
		immI__h32[11:0] == 12'd321 ||
		immI__h32[11:0] == 12'd322 ||
		immI__h32[11:0] == 12'd323 ||
		immI__h32[11:0] == 12'd324 ||
		immI__h32[11:0] == 12'd384 ||
		immI__h32[11:0] == 12'd768 ||
		immI__h32[11:0] == 12'd769 ||
		immI__h32[11:0] == 12'h302 ||
		immI__h32[11:0] == 12'd771 ||
		immI__h32[11:0] == 12'd772 ||
		immI__h32[11:0] == 12'd773 ||
		immI__h32[11:0] == 12'd774 ||
		immI__h32[11:0] == 12'd832 ||
		immI__h32[11:0] == 12'd833 ||
		immI__h32[11:0] == 12'd834 ||
		immI__h32[11:0] == 12'd835 ||
		immI__h32[11:0] == 12'd836 ||
		immI__h32[11:0] == 12'd2816 ||
		immI__h32[11:0] == 12'd2818 ||
		immI__h32[11:0] == 12'd3857 ||
		immI__h32[11:0] == 12'd3858 ||
		immI__h32[11:0] == 12'd3859 ||
		immI__h32[11:0] == 12'd3860 ||
		immI__h32[11:0] == 12'd1952 ||
		immI__h32[11:0] == 12'd1953 ||
		immI__h32[11:0] == 12'd1954 ||
		immI__h32[11:0] == 12'd1955 ||
		immI__h32[11:0] >= 12'd803 && immI__h32[11:0] <= 12'd831 ||
		immI__h32[11:0] >= 12'd2819 && immI__h32[11:0] <= 12'd2847 ||
		immI__h32[11:0] >= 12'd3075 && immI__h32[11:0] <= 12'd3103) ?
		 immI__h32[11:0] :
		 12'd2303,
	       decode_inst[6:0] == 7'd19 || decode_inst[6:0] == 7'd27 ||
	       decode_inst[6:0] == 7'd55 ||
	       decode_inst[6:0] == 7'd23 ||
	       decode_inst[6:0] == 7'd111 ||
	       decode_inst[6:0] == 7'd103 ||
	       decode_inst[6:0] == 7'd99 ||
	       decode_inst[6:0] == 7'd3 ||
	       decode_inst[6:0] == 7'd35 ||
	       decode_inst[6:0] == 7'd47 ||
	       decode_inst[6:0] == 7'd7 ||
	       decode_inst[6:0] == 7'd39 ||
	       decode_inst[6:0] == 7'd115 && decode_inst[14],
	       IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d603,
	       decode_inst[6:0] == 7'd19 || decode_inst[6:0] == 7'd27 ||
	       decode_inst[6:0] == 7'd51 ||
	       decode_inst[6:0] == 7'd59 ||
	       decode_inst[6:0] == 7'd55 ||
	       decode_inst[6:0] == 7'd103 ||
	       decode_inst[6:0] == 7'd99 ||
	       decode_inst[6:0] == 7'd3 ||
	       decode_inst[6:0] == 7'd35 ||
	       decode_inst[6:0] == 7'd47 ||
	       ((decode_inst[6:0] == 7'd83) ?
		  decode_inst[26:25] == 2'b0 || decode_inst[26:25] == 2'b01 :
		  decode_inst[6:0] == 7'd7 || decode_inst[6:0] == 7'd39 ||
		  (decode_inst[6:0] == 7'd67 || decode_inst[6:0] == 7'd71 ||
		   decode_inst[6:0] == 7'd75 ||
		   decode_inst[6:0] == 7'd79) &&
		  (decode_inst[26:25] == 2'b0 ||
		   decode_inst[26:25] == 2'b01)),
	       decode_inst[6:0] != 7'd19 && decode_inst[6:0] != 7'd27 &&
	       decode_inst[6:0] != 7'd51 &&
	       decode_inst[6:0] != 7'd59 &&
	       decode_inst[6:0] != 7'd55 &&
	       decode_inst[6:0] != 7'd103 &&
	       decode_inst[6:0] != 7'd99 &&
	       decode_inst[6:0] != 7'd3 &&
	       decode_inst[6:0] != 7'd35 &&
	       decode_inst[6:0] != 7'd47 &&
	       ((decode_inst[6:0] == 7'd83) ?
		  decode_inst[31:27] != 5'b11110 &&
		  decode_inst[31:27] != 5'b11010 :
		  decode_inst[6:0] != 7'd7 && decode_inst[6:0] != 7'd39),
	       (decode_inst[6:0] == 7'd19 || decode_inst[6:0] == 7'd27 ||
		decode_inst[6:0] == 7'd51 ||
		decode_inst[6:0] == 7'd59 ||
		decode_inst[6:0] == 7'd55 ||
		decode_inst[6:0] == 7'd103 ||
		decode_inst[6:0] == 7'd99 ||
		decode_inst[6:0] == 7'd3 ||
		decode_inst[6:0] == 7'd35 ||
		decode_inst[6:0] == 7'd47 ||
		((decode_inst[6:0] == 7'd83) ?
		   decode_inst[31:27] == 5'b11110 ||
		   decode_inst[31:27] == 5'b11010 :
		   decode_inst[6:0] == 7'd7 || decode_inst[6:0] == 7'd39)) ?
		 CASE_decode_inst_BITS_6_TO_0_3_decode_inst_BIT_ETC__q33 :
		 ((decode_inst[6:0] == 7'd83) ?
		    CASE_decode_inst_BITS_31_TO_27_0b1000_decode_i_ETC__q34 :
		    decode_inst[19:15]),
	       decode_inst[6:0] == 7'd51 || decode_inst[6:0] == 7'd59 ||
	       decode_inst[6:0] == 7'd99 ||
	       decode_inst[6:0] == 7'd35 ||
	       CASE_decode_inst_BITS_6_TO_0_47_NOT_decode_ins_ETC__q36,
	       decode_inst[6:0] == 7'd83 || decode_inst[6:0] == 7'd39 ||
	       decode_inst[6:0] == 7'd67 ||
	       decode_inst[6:0] == 7'd71 ||
	       decode_inst[6:0] == 7'd75 ||
	       decode_inst[6:0] == 7'd79,
	       (decode_inst[6:0] != 7'd83 && decode_inst[6:0] != 7'd39 &&
		decode_inst[6:0] != 7'd67 &&
		decode_inst[6:0] != 7'd71 &&
		decode_inst[6:0] != 7'd75 &&
		decode_inst[6:0] != 7'd79) ?
		 CASE_decode_inst_BITS_6_TO_0_35_decode_inst_BI_ETC__q37 :
		 decode_inst[24:20],
	       (decode_inst[6:0] == 7'd67 || decode_inst[6:0] == 7'd71 ||
		decode_inst[6:0] == 7'd75 ||
		decode_inst[6:0] == 7'd79) &&
	       (decode_inst[26:25] == 2'b0 || decode_inst[26:25] == 2'b01),
	       decode_inst[31:27],
	       (decode_inst[6:0] != 7'd19 && decode_inst[6:0] != 7'd27 &&
		decode_inst[6:0] != 7'd51 &&
		decode_inst[6:0] != 7'd59 &&
		decode_inst[6:0] != 7'd55 &&
		decode_inst[6:0] != 7'd23 &&
		decode_inst[6:0] != 7'd111 &&
		decode_inst[6:0] != 7'd103 &&
		decode_inst[6:0] != 7'd3 &&
		decode_inst[6:0] != 7'd47 &&
		((decode_inst[6:0] == 7'd83) ?
		   decode_inst[26:25] != 2'b0 && decode_inst[26:25] != 2'b01 :
		   decode_inst[6:0] != 7'd7 &&
		   CASE_decode_inst_BITS_6_TO_0_67_NOT_decode_ins_ETC__q38) ||
		((decode_inst[6:0] == 7'd83) ?
		   decode_inst[31:27] != 5'b10100 &&
		   decode_inst[31:27] != 5'b11100 &&
		   decode_inst[31:27] != 5'b11000 :
		   decode_inst[6:0] == 7'd7 || decode_inst[6:0] == 7'd67 ||
		   decode_inst[6:0] == 7'd71 ||
		   decode_inst[6:0] == 7'd75 ||
		   decode_inst[6:0] == 7'd79) ||
		x__h16500 != 5'd0) &&
	       (decode_inst[6:0] == 7'd19 || decode_inst[6:0] == 7'd27 ||
		decode_inst[6:0] == 7'd51 ||
		decode_inst[6:0] == 7'd59 ||
		decode_inst[6:0] == 7'd55 ||
		decode_inst[6:0] == 7'd23 ||
		decode_inst[6:0] == 7'd111 ||
		decode_inst[6:0] == 7'd103 ||
		decode_inst[6:0] == 7'd3 ||
		decode_inst[6:0] == 7'd47 ||
		((decode_inst[6:0] == 7'd83) ?
		   decode_inst[26:25] == 2'b0 || decode_inst[26:25] == 2'b01 :
		   decode_inst[6:0] == 7'd7 ||
		   CASE_decode_inst_BITS_6_TO_0_67_decode_inst_BI_ETC__q39)),
	       (decode_inst[6:0] == 7'd83) ?
		 decode_inst[31:27] != 5'b10100 &&
		 decode_inst[31:27] != 5'b11100 &&
		 decode_inst[31:27] != 5'b11000 :
		 decode_inst[6:0] == 7'd7 || decode_inst[6:0] == 7'd67 ||
		 decode_inst[6:0] == 7'd71 ||
		 decode_inst[6:0] == 7'd75 ||
		 decode_inst[6:0] == 7'd79,
	       ((decode_inst[6:0] == 7'd83) ?
		  decode_inst[31:27] == 5'b10100 ||
		  decode_inst[31:27] == 5'b11100 ||
		  decode_inst[31:27] == 5'b11000 :
		  decode_inst[6:0] != 7'd7 && decode_inst[6:0] != 7'd67 &&
		  decode_inst[6:0] != 7'd71 &&
		  decode_inst[6:0] != 7'd75 &&
		  decode_inst[6:0] != 7'd79) ?
		 x__h16500 :
		 ((decode_inst[6:0] == 7'd83) ?
		    CASE_decode_inst_BITS_31_TO_27_0b1000_decode_i_ETC__q40 :
		    decode_inst[11:7]),
	       decode_inst[6:0] != 7'd19 && decode_inst[6:0] != 7'd27 &&
	       decode_inst[6:0] != 7'd51 &&
	       decode_inst[6:0] != 7'd59 &&
	       decode_inst[6:0] != 7'd55 &&
	       decode_inst[6:0] != 7'd23 &&
	       decode_inst[6:0] != 7'd111 &&
	       decode_inst[6:0] != 7'd103 &&
	       decode_inst[6:0] != 7'd99 &&
	       CASE_decode_inst_BITS_6_TO_0_3_NOT_decode_inst_ETC__q42 } ;

  // remaining internal signals
  assign IF_NOT_decode_inst_BITS_26_TO_25_4_EQ_0b0_5_6__ETC___d137 =
	     (decode_inst[26:25] != 2'b0 && decode_inst[26:25] != 2'b01) ?
	       3'd5 :
	       3'd4 ;
  assign IF_NOT_decode_inst_BITS_26_TO_25_4_EQ_0b0_5_6__ETC___d30 =
	     (decode_inst[26:25] != 2'b0 && decode_inst[26:25] != 2'b01) ?
	       5'd0 :
	       5'd12 ;
  assign IF_NOT_decode_inst_BITS_6_TO_0_EQ_51_09_AND_NO_ETC___d449 =
	     (decode_inst[6:0] != 7'd51 && decode_inst[6:0] != 7'd59 &&
	      decode_inst[6:0] != 7'd55 &&
	      decode_inst[6:0] != 7'd23 &&
	      decode_inst[6:0] != 7'd111 &&
	      decode_inst[6:0] != 7'd103 &&
	      decode_inst[6:0] != 7'd99 &&
	      CASE_decode_inst_BITS_6_TO_0_3_decode_inst_BIT_ETC__q19) ?
	       IF_decode_inst_BITS_6_TO_0_EQ_3_5_THEN_IF_NOT__ETC___d374 :
	       (((decode_inst[6:0] == 7'd51) ?
		   decode_inst[31:25] == 7'b0000001 :
		   decode_inst[6:0] == 7'd59 &&
		   decode_inst[31:25] == 7'b0000001) ?
		  { 13'h0AAA,
		    CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_1_0b1_ETC__q20,
		    decode_inst[6:0] != 7'd51,
		    CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_0_0b1_ETC__q21 } :
		  { 9'h0AA,
		    CASE_decode_inst_BITS_6_TO_0_67_25_71_26_75_27_ETC__q27,
		    decode_inst[14:12],
		    decode_inst[26:25] != 2'b0 }) ;
  assign IF_decode_inst_BITS_14_TO_12_1_EQ_0b0_3_OR_dec_ETC___d116 =
	     (decode_inst[14:12] == 3'b0 || decode_inst[14:12] == 3'b001 ||
	      decode_inst[14:12] == 3'b010 ||
	      decode_inst[14:12] == 3'b011 ||
	      decode_inst[14:12] == 3'b100 ||
	      decode_inst[14:12] == 3'b101 ||
	      decode_inst[14:12] == 3'b110) ?
	       3'd2 :
	       3'd5 ;
  assign IF_decode_inst_BITS_14_TO_12_1_EQ_0b101_00_THE_ETC___d171 =
	     immI__h32[10] ? 5'd11 : 5'd13 ;
  assign IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d451 =
	     (decode_inst[6:0] == 7'd19 || decode_inst[6:0] == 7'd27 ||
	      CASE_decode_inst_BITS_6_TO_0_51_decode_inst_BI_ETC__q28) ?
	       { 13'h0AAA,
		 IF_decode_inst_BITS_6_TO_0_EQ_19_THEN_IF_decod_ETC___d207 } :
	       ((decode_inst[6:0] == 7'd111 || decode_inst[6:0] == 7'd103 ||
		 decode_inst[6:0] == 7'd99) ?
		  { 15'h2AAA,
		    CASE_decode_inst_BITS_6_TO_0_103_6_111_6_CASE__ETC__q30 } :
		  IF_NOT_decode_inst_BITS_6_TO_0_EQ_51_09_AND_NO_ETC___d449) ;
  assign IF_decode_inst_BITS_6_TO_0_EQ_3_5_THEN_IF_NOT__ETC___d374 =
	     { CASE_decode_inst_BITS_6_TO_0_3_0_7_0_35_IF_dec_ETC__q12,
	       CASE_decode_inst_BITS_6_TO_0_3_9_7_9_35_9_39_9_ETC__q14,
	       CASE_decode_inst_BITS_6_TO_0_3_decode_inst_BIT_ETC__q16,
	       CASE_decode_inst_BITS_6_TO_0_3_decode_inst_BIT_ETC__q17,
	       IF_decode_inst_BITS_6_TO_0_EQ_3_5_OR_decode_in_ETC___d372 } ;
  assign IF_decode_inst_BITS_6_TO_0_EQ_47_7_THEN_IF_dec_ETC___d308 =
	     (decode_inst[6:0] == 7'd47) ?
	       CASE_decode_inst_BITS_31_TO_27_0b0_1_0b1_0_0b1_ETC__q4 :
	       4'd9 ;
  assign decode_inst_BITS_31_TO_20__q2 = decode_inst[31:20] ;
  assign decode_inst_BIT_23_4_OR_decode_inst_BIT_21_5___d46 =
	     decode_inst[23] | decode_inst[21] ;
  assign decode_inst_BIT_26_7_OR_decode_inst_BIT_24_8___d49 =
	     decode_inst[26] | decode_inst[24] ;
  assign immB__h34 = { {19{x__h15801[12]}}, x__h15801 } ;
  assign immI__h32 =
	     { {20{decode_inst_BITS_31_TO_20__q2[11]}},
	       decode_inst_BITS_31_TO_20__q2 } ;
  assign immJ__h36 = { {11{x__h15713[20]}}, x__h15713 } ;
  assign immS__h33 = { {20{x__h15888[11]}}, x__h15888 } ;
  assign immU__h35 = { decode_inst[31:12], 12'b0 } ;
  assign x__h15713 =
	     { decode_inst[31],
	       decode_inst[19:12],
	       decode_inst[20],
	       decode_inst[30:21],
	       1'b0 } ;
  assign x__h15801 =
	     { decode_inst[31],
	       decode_inst[7],
	       decode_inst[30:25],
	       decode_inst[11:8],
	       1'b0 } ;
  assign x__h15888 = { decode_inst[31:25], decode_inst[11:7] } ;
  always@(decode_inst)
  begin
    case (decode_inst[31:27])
      5'b10100, 5'b11100:
	  CASE_decode_inst_BITS_31_TO_27_0b10100_decode__ETC__q1 =
	      decode_inst[11:7];
      default: CASE_decode_inst_BITS_31_TO_27_0b10100_decode__ETC__q1 =
		   decode_inst[11:7];
    endcase
  end
  always@(decode_inst or
	  CASE_decode_inst_BITS_31_TO_27_0b10100_decode__ETC__q1)
  begin
    case (decode_inst[6:0])
      7'd3, 7'd19, 7'd23, 7'd27, 7'd47, 7'd51, 7'd55, 7'd59, 7'd103, 7'd111:
	  x__h16500 = decode_inst[11:7];
      7'd83:
	  x__h16500 = CASE_decode_inst_BITS_31_TO_27_0b10100_decode__ETC__q1;
      default: x__h16500 = decode_inst[11:7];
    endcase
  end
  always@(decode_inst or
	  decode_inst_BIT_23_4_OR_decode_inst_BIT_21_5___d46 or
	  decode_inst_BIT_26_7_OR_decode_inst_BIT_24_8___d49)
  begin
    case (decode_inst[6:0])
      7'd7, 7'd39:
	  IF_decode_inst_BITS_6_TO_0_EQ_7_1_OR_decode_in_ETC___d234 =
	      decode_inst[14:12] == 3'b0 || decode_inst[14:12] == 3'b001 ||
	      decode_inst[14:12] == 3'b010 ||
	      decode_inst[14:12] == 3'b011 ||
	      decode_inst[14:12] == 3'b100 ||
	      decode_inst[14:12] == 3'b101 ||
	      decode_inst[14:12] == 3'b110;
      default: IF_decode_inst_BITS_6_TO_0_EQ_7_1_OR_decode_in_ETC___d234 =
		   decode_inst[6:0] == 7'd15 && decode_inst[14:12] == 3'b0 &&
		   (decode_inst_BIT_23_4_OR_decode_inst_BIT_21_5___d46 ||
		    decode_inst_BIT_26_7_OR_decode_inst_BIT_24_8___d49);
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[31:27])
      5'b0,
      5'b00001,
      5'b00100,
      5'b01000,
      5'b01100,
      5'b10000,
      5'b10100,
      5'b11000,
      5'b11100:
	  CASE_decode_inst_BITS_31_TO_27_0b0_4_0b1_4_0b1_ETC__q3 = 3'd4;
      5'b00010: CASE_decode_inst_BITS_31_TO_27_0b0_4_0b1_4_0b1_ETC__q3 = 3'd2;
      5'b00011: CASE_decode_inst_BITS_31_TO_27_0b0_4_0b1_4_0b1_ETC__q3 = 3'd3;
      default: CASE_decode_inst_BITS_31_TO_27_0b0_4_0b1_4_0b1_ETC__q3 = 3'd0;
    endcase
  end
  always@(decode_inst or
	  CASE_decode_inst_BITS_31_TO_27_0b0_4_0b1_4_0b1_ETC__q3)
  begin
    case (decode_inst[6:0])
      7'd35, 7'd39:
	  IF_decode_inst_BITS_6_TO_0_EQ_35_6_OR_decode_i_ETC___d263 = 3'd1;
      7'd47:
	  IF_decode_inst_BITS_6_TO_0_EQ_35_6_OR_decode_i_ETC___d263 =
	      CASE_decode_inst_BITS_31_TO_27_0b0_4_0b1_4_0b1_ETC__q3;
      default: IF_decode_inst_BITS_6_TO_0_EQ_35_6_OR_decode_i_ETC___d263 =
		   3'd0;
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[31:27])
      5'b0: CASE_decode_inst_BITS_31_TO_27_0b0_1_0b1_0_0b1_ETC__q4 = 4'd1;
      5'b00001: CASE_decode_inst_BITS_31_TO_27_0b0_1_0b1_0_0b1_ETC__q4 = 4'd0;
      5'b00100: CASE_decode_inst_BITS_31_TO_27_0b0_1_0b1_0_0b1_ETC__q4 = 4'd2;
      5'b01000: CASE_decode_inst_BITS_31_TO_27_0b0_1_0b1_0_0b1_ETC__q4 = 4'd4;
      5'b01100: CASE_decode_inst_BITS_31_TO_27_0b0_1_0b1_0_0b1_ETC__q4 = 4'd3;
      5'b10000: CASE_decode_inst_BITS_31_TO_27_0b0_1_0b1_0_0b1_ETC__q4 = 4'd5;
      5'b10100: CASE_decode_inst_BITS_31_TO_27_0b0_1_0b1_0_0b1_ETC__q4 = 4'd6;
      5'b11000: CASE_decode_inst_BITS_31_TO_27_0b0_1_0b1_0_0b1_ETC__q4 = 4'd7;
      5'b11100: CASE_decode_inst_BITS_31_TO_27_0b0_1_0b1_0_0b1_ETC__q4 = 4'd8;
      default: CASE_decode_inst_BITS_31_TO_27_0b0_1_0b1_0_0b1_ETC__q4 = 4'd9;
    endcase
  end
  always@(decode_inst or
	  decode_inst_BIT_23_4_OR_decode_inst_BIT_21_5___d46 or
	  decode_inst_BIT_26_7_OR_decode_inst_BIT_24_8___d49)
  begin
    case (decode_inst[6:0])
      7'd3, 7'd7, 7'd35, 7'd39, 7'd47:
	  IF_decode_inst_BITS_6_TO_0_EQ_3_5_OR_decode_in_ETC___d372 =
	      { decode_inst[6:0] == 7'd47 && decode_inst[26],
		decode_inst[6:0] == 7'd47 && decode_inst[25] };
      default: IF_decode_inst_BITS_6_TO_0_EQ_3_5_OR_decode_in_ETC___d372 =
		   { decode_inst_BIT_23_4_OR_decode_inst_BIT_21_5___d46,
		     decode_inst_BIT_26_7_OR_decode_inst_BIT_24_8___d49 };
    endcase
  end
  always@(decode_inst or
	  immI__h32 or immU__h35 or immS__h33 or immB__h34 or immJ__h36)
  begin
    case (decode_inst[6:0])
      7'd3, 7'd7, 7'd19, 7'd27, 7'd103:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d603 =
	      immI__h32;
      7'd23, 7'd55:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d603 =
	      immU__h35;
      7'd35, 7'd39:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d603 =
	      immS__h33;
      7'd47:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d603 = 32'd0;
      7'd99:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d603 =
	      immB__h34;
      7'd111:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d603 =
	      immJ__h36;
      default: IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d603 =
		   { 27'd0, decode_inst[19:15] };
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[14:12])
      3'b001, 3'b101:
	  CASE_decode_inst_BITS_14_TO_12_0b1_15_0b10_16__ETC__q5 = 5'd15;
      3'b010, 3'b110:
	  CASE_decode_inst_BITS_14_TO_12_0b1_15_0b10_16__ETC__q5 = 5'd16;
      default: CASE_decode_inst_BITS_14_TO_12_0b1_15_0b10_16__ETC__q5 = 5'd17;
    endcase
  end
  always@(decode_inst or
	  IF_decode_inst_BITS_14_TO_12_1_EQ_0b101_00_THE_ETC___d171)
  begin
    case (decode_inst[14:12])
      3'b0: CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q6 = 5'd0;
      3'b001: CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q6 = 5'd9;
      3'b010: CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q6 = 5'd7;
      3'b011: CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q6 = 5'd8;
      3'b100: CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q6 = 5'd6;
      3'd5:
	  CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q6 =
	      IF_decode_inst_BITS_14_TO_12_1_EQ_0b101_00_THE_ETC___d171;
      3'b110: CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q6 = 5'd5;
      3'b111: CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q6 = 5'd4;
    endcase
  end
  always@(decode_inst or immI__h32)
  begin
    case (decode_inst[14:12])
      3'b0: CASE_decode_inst_BITS_14_TO_12_0b0_1_0b1_10_IF_ETC__q7 = 5'd1;
      3'b001: CASE_decode_inst_BITS_14_TO_12_0b0_1_0b1_10_IF_ETC__q7 = 5'd10;
      default: CASE_decode_inst_BITS_14_TO_12_0b0_1_0b1_10_IF_ETC__q7 =
		   immI__h32[10] ? 5'd12 : 5'd14;
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[14:12])
      3'b0: CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q8 = 5'd0;
      3'b001: CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q8 = 5'd9;
      3'b010: CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q8 = 5'd7;
      3'b011: CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q8 = 5'd8;
      3'b100: CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q8 = 5'd6;
      3'd5: CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q8 = 5'd13;
      3'b110: CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q8 = 5'd5;
      3'b111: CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q8 = 5'd4;
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[14:12])
      3'b0: CASE_decode_inst_BITS_14_TO_12_0b0_1_0b1_10_14__q9 = 5'd1;
      3'b001: CASE_decode_inst_BITS_14_TO_12_0b0_1_0b1_10_14__q9 = 5'd10;
      default: CASE_decode_inst_BITS_14_TO_12_0b0_1_0b1_10_14__q9 = 5'd14;
    endcase
  end
  always@(decode_inst or
	  CASE_decode_inst_BITS_14_TO_12_0b1_15_0b10_16__ETC__q5 or
	  CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q6 or
	  CASE_decode_inst_BITS_14_TO_12_0b0_1_0b1_10_IF_ETC__q7 or
	  CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q8 or
	  CASE_decode_inst_BITS_14_TO_12_0b0_1_0b1_10_14__q9)
  begin
    case (decode_inst[6:0])
      7'd19:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_THEN_IF_decod_ETC___d207 =
	      CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q6;
      7'd23, 7'd55:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_THEN_IF_decod_ETC___d207 = 5'd0;
      7'd27:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_THEN_IF_decod_ETC___d207 =
	      CASE_decode_inst_BITS_14_TO_12_0b0_1_0b1_10_IF_ETC__q7;
      7'd51:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_THEN_IF_decod_ETC___d207 =
	      (decode_inst[31:25] == 7'b0) ?
		CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_9_0b1_ETC__q8 :
		((decode_inst[14:12] == 3'b0) ? 5'd2 : 5'd11);
      7'd59:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_THEN_IF_decod_ETC___d207 =
	      (decode_inst[31:25] == 7'b0) ?
		CASE_decode_inst_BITS_14_TO_12_0b0_1_0b1_10_14__q9 :
		((decode_inst[14:12] == 3'b0) ? 5'd3 : 5'd12);
      default: IF_decode_inst_BITS_6_TO_0_EQ_19_THEN_IF_decod_ETC___d207 =
		   CASE_decode_inst_BITS_14_TO_12_0b1_15_0b10_16__ETC__q5;
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[31:25])
      7'b0, 7'b0100000:
	  IF_decode_inst_BITS_31_TO_25_5_EQ_0b0_8_OR_dec_ETC___d93 = 3'd0;
      7'b0000001:
	  IF_decode_inst_BITS_31_TO_25_5_EQ_0b0_8_OR_dec_ETC___d93 = 3'd3;
      default: IF_decode_inst_BITS_31_TO_25_5_EQ_0b0_8_OR_dec_ETC___d93 =
		   3'd5;
    endcase
  end
  always@(decode_inst or
	  decode_inst_BIT_23_4_OR_decode_inst_BIT_21_5___d46 or
	  decode_inst_BIT_26_7_OR_decode_inst_BIT_24_8___d49)
  begin
    case (decode_inst[14:12])
      3'b0:
	  IF_decode_inst_BITS_14_TO_12_1_EQ_0b1_2_THEN_5_ETC___d141 =
	      (decode_inst_BIT_23_4_OR_decode_inst_BIT_21_5___d46 ||
	       decode_inst_BIT_26_7_OR_decode_inst_BIT_24_8___d49) ?
		3'd2 :
		3'd5;
      3'b001:
	  IF_decode_inst_BITS_14_TO_12_1_EQ_0b1_2_THEN_5_ETC___d141 = 3'd5;
      default: IF_decode_inst_BITS_14_TO_12_1_EQ_0b1_2_THEN_5_ETC___d141 =
		   3'd5;
    endcase
  end
  always@(decode_inst or
	  IF_decode_inst_BITS_14_TO_12_1_EQ_0b0_3_OR_dec_ETC___d116)
  begin
    case (decode_inst[31:27])
      5'b0,
      5'b00001,
      5'b00010,
      5'b00011,
      5'b00100,
      5'b01000,
      5'b01100,
      5'b10000,
      5'b10100,
      5'b11000,
      5'b11100:
	  CASE_decode_inst_BITS_31_TO_27_0b0_IF_decode_i_ETC__q10 =
	      IF_decode_inst_BITS_14_TO_12_1_EQ_0b0_3_OR_dec_ETC___d116;
      default: CASE_decode_inst_BITS_31_TO_27_0b0_IF_decode_i_ETC__q10 = 3'd5;
    endcase
  end
  always@(decode_inst or
	  IF_decode_inst_BITS_14_TO_12_1_EQ_0b0_3_OR_dec_ETC___d116 or
	  IF_decode_inst_BITS_14_TO_12_1_EQ_0b1_2_THEN_5_ETC___d141 or
	  CASE_decode_inst_BITS_31_TO_27_0b0_IF_decode_i_ETC__q10 or
	  IF_decode_inst_BITS_31_TO_25_5_EQ_0b0_8_OR_dec_ETC___d93 or
	  IF_NOT_decode_inst_BITS_26_TO_25_4_EQ_0b0_5_6__ETC___d137)
  begin
    case (decode_inst[6:0])
      7'd3, 7'd7, 7'd35, 7'd39:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d160 =
	      IF_decode_inst_BITS_14_TO_12_1_EQ_0b0_3_OR_dec_ETC___d116;
      7'd15:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d160 =
	      IF_decode_inst_BITS_14_TO_12_1_EQ_0b1_2_THEN_5_ETC___d141;
      7'd19, 7'd23, 7'd27, 7'd55:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d160 = 3'd0;
      7'd47:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d160 =
	      CASE_decode_inst_BITS_31_TO_27_0b0_IF_decode_i_ETC__q10;
      7'd51, 7'd59:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d160 =
	      IF_decode_inst_BITS_31_TO_25_5_EQ_0b0_8_OR_dec_ETC___d93;
      7'd67, 7'd71, 7'd75, 7'd79, 7'd83:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d160 =
	      IF_NOT_decode_inst_BITS_26_TO_25_4_EQ_0b0_5_6__ETC___d137;
      7'd99, 7'd103, 7'd111:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d160 = 3'd1;
      7'd115:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d160 =
	      (decode_inst[14:12] == 3'b0) ? 3'd5 : 3'd0;
      default: IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d160 =
		   3'd5;
    endcase
  end
  always@(decode_inst or
	  IF_decode_inst_BITS_6_TO_0_EQ_35_6_OR_decode_i_ETC___d263)
  begin
    case (decode_inst[31:27])
      5'b00010, 5'b00011:
	  CASE_decode_inst_BITS_31_TO_27_0b10_IF_decode__ETC__q11 =
	      IF_decode_inst_BITS_6_TO_0_EQ_35_6_OR_decode_i_ETC___d263;
      default: CASE_decode_inst_BITS_31_TO_27_0b10_IF_decode__ETC__q11 =
		   IF_decode_inst_BITS_6_TO_0_EQ_35_6_OR_decode_i_ETC___d263;
    endcase
  end
  always@(decode_inst or
	  IF_decode_inst_BITS_6_TO_0_EQ_35_6_OR_decode_i_ETC___d263 or
	  CASE_decode_inst_BITS_31_TO_27_0b10_IF_decode__ETC__q11)
  begin
    case (decode_inst[6:0])
      7'd3, 7'd7:
	  CASE_decode_inst_BITS_6_TO_0_3_0_7_0_35_IF_dec_ETC__q12 = 3'd0;
      7'd35, 7'd39:
	  CASE_decode_inst_BITS_6_TO_0_3_0_7_0_35_IF_dec_ETC__q12 =
	      IF_decode_inst_BITS_6_TO_0_EQ_35_6_OR_decode_i_ETC___d263;
      7'd47:
	  CASE_decode_inst_BITS_6_TO_0_3_0_7_0_35_IF_dec_ETC__q12 =
	      CASE_decode_inst_BITS_31_TO_27_0b10_IF_decode__ETC__q11;
      default: CASE_decode_inst_BITS_6_TO_0_3_0_7_0_35_IF_dec_ETC__q12 = 3'd5;
    endcase
  end
  always@(decode_inst or
	  IF_decode_inst_BITS_6_TO_0_EQ_47_7_THEN_IF_dec_ETC___d308)
  begin
    case (decode_inst[31:27])
      5'b00010, 5'b00011:
	  CASE_decode_inst_BITS_31_TO_27_0b10_IF_decode__ETC__q13 =
	      IF_decode_inst_BITS_6_TO_0_EQ_47_7_THEN_IF_dec_ETC___d308;
      default: CASE_decode_inst_BITS_31_TO_27_0b10_IF_decode__ETC__q13 =
		   IF_decode_inst_BITS_6_TO_0_EQ_47_7_THEN_IF_dec_ETC___d308;
    endcase
  end
  always@(decode_inst or
	  CASE_decode_inst_BITS_31_TO_27_0b10_IF_decode__ETC__q13)
  begin
    case (decode_inst[6:0])
      7'd3, 7'd7, 7'd35, 7'd39:
	  CASE_decode_inst_BITS_6_TO_0_3_9_7_9_35_9_39_9_ETC__q14 = 4'd9;
      7'd47:
	  CASE_decode_inst_BITS_6_TO_0_3_9_7_9_35_9_39_9_ETC__q14 =
	      CASE_decode_inst_BITS_31_TO_27_0b10_IF_decode__ETC__q13;
      default: CASE_decode_inst_BITS_6_TO_0_3_9_7_9_35_9_39_9_ETC__q14 = 4'd9;
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[31:27])
      5'b00010, 5'b00011:
	  CASE_decode_inst_BITS_31_TO_27_0b10_decode_ins_ETC__q15 =
	      decode_inst[14:12] == 3'b100 || decode_inst[14:12] == 3'b101 ||
	      decode_inst[14:12] == 3'b110;
      default: CASE_decode_inst_BITS_31_TO_27_0b10_decode_ins_ETC__q15 =
		   decode_inst[14:12] == 3'b100 ||
		   decode_inst[14:12] == 3'b101 ||
		   decode_inst[14:12] == 3'b110;
    endcase
  end
  always@(decode_inst or
	  CASE_decode_inst_BITS_31_TO_27_0b10_decode_ins_ETC__q15)
  begin
    case (decode_inst[6:0])
      7'd3, 7'd35:
	  CASE_decode_inst_BITS_6_TO_0_3_decode_inst_BIT_ETC__q16 =
	      decode_inst[14:12] == 3'b100 || decode_inst[14:12] == 3'b101 ||
	      decode_inst[14:12] == 3'b110;
      7'd47:
	  CASE_decode_inst_BITS_6_TO_0_3_decode_inst_BIT_ETC__q16 =
	      CASE_decode_inst_BITS_31_TO_27_0b10_decode_ins_ETC__q15;
      default: CASE_decode_inst_BITS_6_TO_0_3_decode_inst_BIT_ETC__q16 =
		   decode_inst[6:0] == 7'd7 ||
		   decode_inst[6:0] == 7'd39 &&
		   (decode_inst[14:12] == 3'b100 ||
		    decode_inst[14:12] == 3'b101 ||
		    decode_inst[14:12] == 3'b110);
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[6:0])
      7'd3, 7'd7, 7'd35, 7'd47:
	  CASE_decode_inst_BITS_6_TO_0_3_decode_inst_BIT_ETC__q17 =
	      { decode_inst[14:12] == 3'b011,
		decode_inst[14:12] == 3'b011,
		decode_inst[14:12] == 3'b011,
		decode_inst[14:12] == 3'b011,
		decode_inst[14:12] == 3'b010 ||
		decode_inst[14:12] == 3'b110 ||
		decode_inst[14:12] == 3'b011,
		decode_inst[14:12] == 3'b010 ||
		decode_inst[14:12] == 3'b110 ||
		decode_inst[14:12] == 3'b011,
		decode_inst[14:12] == 3'b001 ||
		decode_inst[14:12] == 3'b101 ||
		decode_inst[14:12] == 3'b010 ||
		decode_inst[14:12] == 3'b110 ||
		decode_inst[14:12] == 3'b011,
		decode_inst[14:12] == 3'b0 || decode_inst[14:12] == 3'b100 ||
		decode_inst[14:12] == 3'b001 ||
		decode_inst[14:12] == 3'b101 ||
		decode_inst[14:12] == 3'b010 ||
		decode_inst[14:12] == 3'b110 ||
		decode_inst[14:12] == 3'b011 };
      default: CASE_decode_inst_BITS_6_TO_0_3_decode_inst_BIT_ETC__q17 =
		   { decode_inst[6:0] == 7'd39 &&
		     decode_inst[14:12] == 3'b011,
		     decode_inst[6:0] == 7'd39 &&
		     decode_inst[14:12] == 3'b011,
		     decode_inst[6:0] == 7'd39 &&
		     decode_inst[14:12] == 3'b011,
		     decode_inst[6:0] == 7'd39 &&
		     decode_inst[14:12] == 3'b011,
		     decode_inst[6:0] == 7'd39 &&
		     (decode_inst[14:12] == 3'b010 ||
		      decode_inst[14:12] == 3'b110 ||
		      decode_inst[14:12] == 3'b011),
		     decode_inst[6:0] == 7'd39 &&
		     (decode_inst[14:12] == 3'b010 ||
		      decode_inst[14:12] == 3'b110 ||
		      decode_inst[14:12] == 3'b011),
		     decode_inst[6:0] == 7'd39 &&
		     (decode_inst[14:12] == 3'b001 ||
		      decode_inst[14:12] == 3'b101 ||
		      decode_inst[14:12] == 3'b010 ||
		      decode_inst[14:12] == 3'b110 ||
		      decode_inst[14:12] == 3'b011),
		     decode_inst[6:0] == 7'd39 };
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[31:27])
      5'b00010, 5'b00011:
	  CASE_decode_inst_BITS_31_TO_27_0b10_decode_ins_ETC__q18 =
	      decode_inst[14:12] == 3'b0 || decode_inst[14:12] == 3'b001 ||
	      decode_inst[14:12] == 3'b010 ||
	      decode_inst[14:12] == 3'b011 ||
	      decode_inst[14:12] == 3'b100 ||
	      decode_inst[14:12] == 3'b101 ||
	      decode_inst[14:12] == 3'b110;
      default: CASE_decode_inst_BITS_31_TO_27_0b10_decode_ins_ETC__q18 =
		   (decode_inst[31:27] == 5'b00001 ||
		    decode_inst[31:27] == 5'b0 ||
		    decode_inst[31:27] == 5'b00100 ||
		    decode_inst[31:27] == 5'b01100 ||
		    decode_inst[31:27] == 5'b01000 ||
		    decode_inst[31:27] == 5'b10000 ||
		    decode_inst[31:27] == 5'b10100 ||
		    decode_inst[31:27] == 5'b11000 ||
		    decode_inst[31:27] == 5'b11100) &&
		   (decode_inst[14:12] == 3'b0 ||
		    decode_inst[14:12] == 3'b001 ||
		    decode_inst[14:12] == 3'b010 ||
		    decode_inst[14:12] == 3'b011 ||
		    decode_inst[14:12] == 3'b100 ||
		    decode_inst[14:12] == 3'b101 ||
		    decode_inst[14:12] == 3'b110);
    endcase
  end
  always@(decode_inst or
	  IF_decode_inst_BITS_6_TO_0_EQ_7_1_OR_decode_in_ETC___d234 or
	  CASE_decode_inst_BITS_31_TO_27_0b10_decode_ins_ETC__q18)
  begin
    case (decode_inst[6:0])
      7'd3, 7'd35:
	  CASE_decode_inst_BITS_6_TO_0_3_decode_inst_BIT_ETC__q19 =
	      decode_inst[14:12] == 3'b0 || decode_inst[14:12] == 3'b001 ||
	      decode_inst[14:12] == 3'b010 ||
	      decode_inst[14:12] == 3'b011 ||
	      decode_inst[14:12] == 3'b100 ||
	      decode_inst[14:12] == 3'b101 ||
	      decode_inst[14:12] == 3'b110;
      7'd47:
	  CASE_decode_inst_BITS_6_TO_0_3_decode_inst_BIT_ETC__q19 =
	      CASE_decode_inst_BITS_31_TO_27_0b10_decode_ins_ETC__q18;
      default: CASE_decode_inst_BITS_6_TO_0_3_decode_inst_BIT_ETC__q19 =
		   decode_inst[6:0] != 7'd83 &&
		   IF_decode_inst_BITS_6_TO_0_EQ_7_1_OR_decode_in_ETC___d234;
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[14:12])
      3'b0: CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_1_0b1_ETC__q20 = 2'd0;
      3'b001, 3'b010, 3'b011:
	  CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_1_0b1_ETC__q20 = 2'd1;
      3'b100, 3'b101:
	  CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_1_0b1_ETC__q20 = 2'd2;
      default: CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_1_0b1_ETC__q20 = 2'd3;
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[14:12])
      3'b0, 3'b001, 3'b100, 3'b110:
	  CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_0_0b1_ETC__q21 = 2'd0;
      3'b010: CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_0_0b1_ETC__q21 = 2'd2;
      3'b011, 3'b101, 3'd7:
	  CASE_decode_inst_BITS_14_TO_12_0b0_0_0b1_0_0b1_ETC__q21 = 2'd1;
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[24:20])
      5'd0: CASE_decode_inst_BITS_24_TO_20_0_15_1_16_2_17_18__q22 = 5'd15;
      5'd1: CASE_decode_inst_BITS_24_TO_20_0_15_1_16_2_17_18__q22 = 5'd16;
      5'd2: CASE_decode_inst_BITS_24_TO_20_0_15_1_16_2_17_18__q22 = 5'd17;
      default: CASE_decode_inst_BITS_24_TO_20_0_15_1_16_2_17_18__q22 = 5'd18;
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[14:12])
      3'b0: CASE_decode_inst_BITS_14_TO_12_0b0_5_0b1_6_7__q23 = 5'd5;
      3'b001: CASE_decode_inst_BITS_14_TO_12_0b0_5_0b1_6_7__q23 = 5'd6;
      default: CASE_decode_inst_BITS_14_TO_12_0b0_5_0b1_6_7__q23 = 5'd7;
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[14:12])
      3'b0: CASE_decode_inst_BITS_14_TO_12_0b0_21_0b1_20_19__q24 = 5'd21;
      3'b001: CASE_decode_inst_BITS_14_TO_12_0b0_21_0b1_20_19__q24 = 5'd20;
      default: CASE_decode_inst_BITS_14_TO_12_0b0_21_0b1_20_19__q24 = 5'd19;
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[24:20])
      5'd0: CASE_decode_inst_BITS_24_TO_20_0_11_1_12_2_13_14__q25 = 5'd11;
      5'd1: CASE_decode_inst_BITS_24_TO_20_0_11_1_12_2_13_14__q25 = 5'd12;
      5'd2: CASE_decode_inst_BITS_24_TO_20_0_11_1_12_2_13_14__q25 = 5'd13;
      default: CASE_decode_inst_BITS_24_TO_20_0_11_1_12_2_13_14__q25 = 5'd14;
    endcase
  end
  always@(decode_inst or
	  CASE_decode_inst_BITS_24_TO_20_0_15_1_16_2_17_18__q22 or
	  CASE_decode_inst_BITS_14_TO_12_0b0_5_0b1_6_7__q23 or
	  CASE_decode_inst_BITS_14_TO_12_0b0_21_0b1_20_19__q24 or
	  CASE_decode_inst_BITS_24_TO_20_0_11_1_12_2_13_14__q25)
  begin
    case (decode_inst[31:27])
      5'b0, 5'b00001, 5'b00010, 5'b00011:
	  CASE_decode_inst_BITS_31_TO_27_0b0_decode_inst_ETC__q26 =
	      decode_inst[31:27];
      5'b00100:
	  CASE_decode_inst_BITS_31_TO_27_0b0_decode_inst_ETC__q26 =
	      CASE_decode_inst_BITS_14_TO_12_0b0_5_0b1_6_7__q23;
      5'b00101:
	  CASE_decode_inst_BITS_31_TO_27_0b0_decode_inst_ETC__q26 =
	      (decode_inst[14:12] == 3'b0) ? 5'd8 : 5'd9;
      5'b01000:
	  CASE_decode_inst_BITS_31_TO_27_0b0_decode_inst_ETC__q26 = 5'd10;
      5'b01011:
	  CASE_decode_inst_BITS_31_TO_27_0b0_decode_inst_ETC__q26 = 5'd4;
      5'b10100:
	  CASE_decode_inst_BITS_31_TO_27_0b0_decode_inst_ETC__q26 =
	      CASE_decode_inst_BITS_14_TO_12_0b0_21_0b1_20_19__q24;
      5'b11000:
	  CASE_decode_inst_BITS_31_TO_27_0b0_decode_inst_ETC__q26 =
	      CASE_decode_inst_BITS_24_TO_20_0_11_1_12_2_13_14__q25;
      5'b11100:
	  CASE_decode_inst_BITS_31_TO_27_0b0_decode_inst_ETC__q26 =
	      (decode_inst[14:12] == 3'b0) ? 5'd23 : 5'd22;
      5'b11110:
	  CASE_decode_inst_BITS_31_TO_27_0b0_decode_inst_ETC__q26 = 5'd24;
      default: CASE_decode_inst_BITS_31_TO_27_0b0_decode_inst_ETC__q26 =
		   CASE_decode_inst_BITS_24_TO_20_0_15_1_16_2_17_18__q22;
    endcase
  end
  always@(decode_inst or
	  CASE_decode_inst_BITS_31_TO_27_0b0_decode_inst_ETC__q26)
  begin
    case (decode_inst[6:0])
      7'd67: CASE_decode_inst_BITS_6_TO_0_67_25_71_26_75_27_ETC__q27 = 5'd25;
      7'd71: CASE_decode_inst_BITS_6_TO_0_67_25_71_26_75_27_ETC__q27 = 5'd26;
      7'd75: CASE_decode_inst_BITS_6_TO_0_67_25_71_26_75_27_ETC__q27 = 5'd27;
      7'd83:
	  CASE_decode_inst_BITS_6_TO_0_67_25_71_26_75_27_ETC__q27 =
	      CASE_decode_inst_BITS_31_TO_27_0b0_decode_inst_ETC__q26;
      default: CASE_decode_inst_BITS_6_TO_0_67_25_71_26_75_27_ETC__q27 =
		   5'd28;
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[6:0])
      7'd51, 7'd59:
	  CASE_decode_inst_BITS_6_TO_0_51_decode_inst_BI_ETC__q28 =
	      decode_inst[31:25] == 7'b0 || decode_inst[31:25] == 7'b0100000;
      default: CASE_decode_inst_BITS_6_TO_0_51_decode_inst_BI_ETC__q28 =
		   decode_inst[6:0] == 7'd55 || decode_inst[6:0] == 7'd23 ||
		   decode_inst[6:0] == 7'd115 &&
		   (decode_inst[14:12] == 3'b101 ||
		    decode_inst[14:12] == 3'b001 ||
		    decode_inst[14:12] == 3'b110 ||
		    decode_inst[14:12] == 3'b010 ||
		    decode_inst[14:12] == 3'b111 ||
		    decode_inst[14:12] == 3'b011);
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[14:12])
      3'b0, 3'b001:
	  CASE_decode_inst_BITS_14_TO_12_0b0_decode_inst_ETC__q29 =
	      decode_inst[14:12];
      3'b100: CASE_decode_inst_BITS_14_TO_12_0b0_decode_inst_ETC__q29 = 3'd2;
      3'b101: CASE_decode_inst_BITS_14_TO_12_0b0_decode_inst_ETC__q29 = 3'd4;
      3'b110: CASE_decode_inst_BITS_14_TO_12_0b0_decode_inst_ETC__q29 = 3'd3;
      default: CASE_decode_inst_BITS_14_TO_12_0b0_decode_inst_ETC__q29 = 3'd5;
    endcase
  end
  always@(decode_inst or
	  CASE_decode_inst_BITS_14_TO_12_0b0_decode_inst_ETC__q29)
  begin
    case (decode_inst[6:0])
      7'd103, 7'd111:
	  CASE_decode_inst_BITS_6_TO_0_103_6_111_6_CASE__ETC__q30 = 3'd6;
      default: CASE_decode_inst_BITS_6_TO_0_103_6_111_6_CASE__ETC__q30 =
		   CASE_decode_inst_BITS_14_TO_12_0b0_decode_inst_ETC__q29;
    endcase
  end
  always@(decode_inst or
	  decode_inst_BIT_23_4_OR_decode_inst_BIT_21_5___d46 or
	  decode_inst_BIT_26_7_OR_decode_inst_BIT_24_8___d49)
  begin
    case (decode_inst[14:12])
      3'b0:
	  IF_decode_inst_BITS_14_TO_12_1_EQ_0b1_2_THEN_1_ETC___d53 =
	      (decode_inst_BIT_23_4_OR_decode_inst_BIT_21_5___d46 ||
	       decode_inst_BIT_26_7_OR_decode_inst_BIT_24_8___d49) ?
		5'd14 :
		5'd1;
      3'b001:
	  IF_decode_inst_BITS_14_TO_12_1_EQ_0b1_2_THEN_1_ETC___d53 = 5'd15;
      default: IF_decode_inst_BITS_14_TO_12_1_EQ_0b1_2_THEN_1_ETC___d53 =
		   5'd0;
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[31:27])
      5'b00010: CASE_decode_inst_BITS_31_TO_27_0b10_6_0b11_7_2__q31 = 5'd6;
      5'b00011: CASE_decode_inst_BITS_31_TO_27_0b10_6_0b11_7_2__q31 = 5'd7;
      default: CASE_decode_inst_BITS_31_TO_27_0b10_6_0b11_7_2__q31 = 5'd2;
    endcase
  end
  always@(immI__h32)
  begin
    case (immI__h32[11:0])
      12'h0: CASE_immI2_BITS_11_TO_0_0x0_17_0x1_18_0x102_19_ETC__q32 = 5'd17;
      12'h001:
	  CASE_immI2_BITS_11_TO_0_0x0_17_0x1_18_0x102_19_ETC__q32 = 5'd18;
      12'h102:
	  CASE_immI2_BITS_11_TO_0_0x0_17_0x1_18_0x102_19_ETC__q32 = 5'd19;
      12'h105: CASE_immI2_BITS_11_TO_0_0x0_17_0x1_18_0x102_19_ETC__q32 = 5'd1;
      12'h302:
	  CASE_immI2_BITS_11_TO_0_0x0_17_0x1_18_0x102_19_ETC__q32 = 5'd20;
      default: CASE_immI2_BITS_11_TO_0_0x0_17_0x1_18_0x102_19_ETC__q32 = 5'd0;
    endcase
  end
  always@(decode_inst or
	  IF_decode_inst_BITS_14_TO_12_1_EQ_0b1_2_THEN_1_ETC___d53 or
	  CASE_decode_inst_BITS_31_TO_27_0b10_6_0b11_7_2__q31 or
	  IF_NOT_decode_inst_BITS_26_TO_25_4_EQ_0b0_5_6__ETC___d30 or
	  CASE_immI2_BITS_11_TO_0_0x0_17_0x1_18_0x102_19_ETC__q32)
  begin
    case (decode_inst[6:0])
      7'd3, 7'd7:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d85 = 5'd4;
      7'd15:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d85 =
	      IF_decode_inst_BITS_14_TO_12_1_EQ_0b1_2_THEN_1_ETC___d53;
      7'd19, 7'd27, 7'd51, 7'd55, 7'd59:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d85 = 5'd3;
      7'd23: IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d85 = 5'd11;
      7'd35, 7'd39:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d85 = 5'd5;
      7'd47:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d85 =
	      CASE_decode_inst_BITS_31_TO_27_0b10_6_0b11_7_2__q31;
      7'd67, 7'd71, 7'd75, 7'd79, 7'd83:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d85 =
	      IF_NOT_decode_inst_BITS_26_TO_25_4_EQ_0b0_5_6__ETC___d30;
      7'd99: IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d85 = 5'd10;
      7'd103: IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d85 = 5'd9;
      7'd111: IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d85 = 5'd8;
      7'd115:
	  IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d85 =
	      (decode_inst[14:12] == 3'b0) ?
		((decode_inst[31:25] == 7'h09) ?
		   5'd16 :
		   CASE_immI2_BITS_11_TO_0_0x0_17_0x1_18_0x102_19_ETC__q32) :
		5'd13;
      default: IF_decode_inst_BITS_6_TO_0_EQ_19_OR_decode_ins_ETC___d85 =
		   5'd0;
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[6:0])
      7'd3, 7'd19, 7'd27, 7'd35, 7'd47, 7'd51, 7'd59, 7'd83, 7'd99, 7'd103:
	  CASE_decode_inst_BITS_6_TO_0_3_decode_inst_BIT_ETC__q33 =
	      decode_inst[19:15];
      7'd55: CASE_decode_inst_BITS_6_TO_0_3_decode_inst_BIT_ETC__q33 = 5'd0;
      default: CASE_decode_inst_BITS_6_TO_0_3_decode_inst_BIT_ETC__q33 =
		   decode_inst[19:15];
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[31:27])
      5'b01000, 5'b01011, 5'b10100, 5'b11000, 5'b11100:
	  CASE_decode_inst_BITS_31_TO_27_0b1000_decode_i_ETC__q34 =
	      decode_inst[19:15];
      default: CASE_decode_inst_BITS_31_TO_27_0b1000_decode_i_ETC__q34 =
		   decode_inst[19:15];
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[6:0])
      7'd67, 7'd71, 7'd75, 7'd79:
	  CASE_decode_inst_BITS_6_TO_0_67_decode_inst_BI_ETC__q35 =
	      decode_inst[26:25] == 2'b0 || decode_inst[26:25] == 2'b01;
      default: CASE_decode_inst_BITS_6_TO_0_67_decode_inst_BI_ETC__q35 =
		   decode_inst[6:0] == 7'd115 && decode_inst[14:12] != 3'b0 &&
		   !decode_inst[14];
    endcase
  end
  always@(decode_inst or
	  CASE_decode_inst_BITS_6_TO_0_67_decode_inst_BI_ETC__q35)
  begin
    case (decode_inst[6:0])
      7'd47:
	  CASE_decode_inst_BITS_6_TO_0_47_NOT_decode_ins_ETC__q36 =
	      decode_inst[31:27] != 5'b00010;
      7'd83:
	  CASE_decode_inst_BITS_6_TO_0_47_NOT_decode_ins_ETC__q36 =
	      (decode_inst[26:25] == 2'b0 || decode_inst[26:25] == 2'b01) &&
	      decode_inst[31:27] != 5'b01011 &&
	      decode_inst[31:27] != 5'b11100 &&
	      decode_inst[31:27] != 5'b11110 &&
	      decode_inst[31:27] != 5'b01000 &&
	      decode_inst[31:27] != 5'b11000 &&
	      decode_inst[31:27] != 5'b11010;
      default: CASE_decode_inst_BITS_6_TO_0_47_NOT_decode_ins_ETC__q36 =
		   decode_inst[6:0] == 7'd39 ||
		   CASE_decode_inst_BITS_6_TO_0_67_decode_inst_BI_ETC__q35;
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[6:0])
      7'd35, 7'd47, 7'd51, 7'd59, 7'd99:
	  CASE_decode_inst_BITS_6_TO_0_35_decode_inst_BI_ETC__q37 =
	      decode_inst[24:20];
      default: CASE_decode_inst_BITS_6_TO_0_35_decode_inst_BI_ETC__q37 =
		   decode_inst[19:15];
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[6:0])
      7'd67, 7'd71, 7'd75, 7'd79:
	  CASE_decode_inst_BITS_6_TO_0_67_NOT_decode_ins_ETC__q38 =
	      decode_inst[26:25] != 2'b0 && decode_inst[26:25] != 2'b01;
      default: CASE_decode_inst_BITS_6_TO_0_67_NOT_decode_ins_ETC__q38 =
		   decode_inst[6:0] != 7'd115 || decode_inst[14:12] == 3'b0;
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[6:0])
      7'd67, 7'd71, 7'd75, 7'd79:
	  CASE_decode_inst_BITS_6_TO_0_67_decode_inst_BI_ETC__q39 =
	      decode_inst[26:25] == 2'b0 || decode_inst[26:25] == 2'b01;
      default: CASE_decode_inst_BITS_6_TO_0_67_decode_inst_BI_ETC__q39 =
		   decode_inst[6:0] == 7'd115 && decode_inst[14:12] != 3'b0;
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[31:27])
      5'b01000, 5'b01011, 5'b11110:
	  CASE_decode_inst_BITS_31_TO_27_0b1000_decode_i_ETC__q40 =
	      decode_inst[11:7];
      default: CASE_decode_inst_BITS_31_TO_27_0b1000_decode_i_ETC__q40 =
		   decode_inst[11:7];
    endcase
  end
  always@(decode_inst)
  begin
    case (decode_inst[31:27])
      5'b00010, 5'b00011:
	  CASE_decode_inst_BITS_31_TO_27_0b10_NOT_decode_ETC__q41 =
	      decode_inst[14:12] != 3'b0 && decode_inst[14:12] != 3'b100 &&
	      decode_inst[14:12] != 3'b001 &&
	      decode_inst[14:12] != 3'b101 &&
	      decode_inst[14:12] != 3'b010 &&
	      decode_inst[14:12] != 3'b110 &&
	      decode_inst[14:12] != 3'b011;
      default: CASE_decode_inst_BITS_31_TO_27_0b10_NOT_decode_ETC__q41 =
		   decode_inst[31:27] != 5'b00001 &&
		   decode_inst[31:27] != 5'b0 &&
		   decode_inst[31:27] != 5'b00100 &&
		   decode_inst[31:27] != 5'b01100 &&
		   decode_inst[31:27] != 5'b01000 &&
		   decode_inst[31:27] != 5'b10000 &&
		   decode_inst[31:27] != 5'b10100 &&
		   decode_inst[31:27] != 5'b11000 &&
		   decode_inst[31:27] != 5'b11100 ||
		   decode_inst[14:12] != 3'b0 &&
		   decode_inst[14:12] != 3'b100 &&
		   decode_inst[14:12] != 3'b001 &&
		   decode_inst[14:12] != 3'b101 &&
		   decode_inst[14:12] != 3'b010 &&
		   decode_inst[14:12] != 3'b110 &&
		   decode_inst[14:12] != 3'b011;
    endcase
  end
  always@(decode_inst or
	  immI__h32 or
	  CASE_decode_inst_BITS_31_TO_27_0b10_NOT_decode_ETC__q41)
  begin
    case (decode_inst[6:0])
      7'd3, 7'd7, 7'd35, 7'd39:
	  CASE_decode_inst_BITS_6_TO_0_3_NOT_decode_inst_ETC__q42 =
	      decode_inst[14:12] != 3'b0 && decode_inst[14:12] != 3'b100 &&
	      decode_inst[14:12] != 3'b001 &&
	      decode_inst[14:12] != 3'b101 &&
	      decode_inst[14:12] != 3'b010 &&
	      decode_inst[14:12] != 3'b110 &&
	      decode_inst[14:12] != 3'b011;
      7'd15:
	  CASE_decode_inst_BITS_6_TO_0_3_NOT_decode_inst_ETC__q42 =
	      decode_inst[14:12] != 3'b001 && decode_inst[14:12] != 3'b0;
      7'd47:
	  CASE_decode_inst_BITS_6_TO_0_3_NOT_decode_inst_ETC__q42 =
	      CASE_decode_inst_BITS_31_TO_27_0b10_NOT_decode_ETC__q41;
      7'd67, 7'd71, 7'd75, 7'd79:
	  CASE_decode_inst_BITS_6_TO_0_3_NOT_decode_inst_ETC__q42 =
	      decode_inst[26:25] != 2'b0 && decode_inst[26:25] != 2'b01 ||
	      decode_inst[6:0] != 7'd67 && decode_inst[6:0] != 7'd71 &&
	      decode_inst[6:0] != 7'd75 &&
	      decode_inst[6:0] != 7'd79;
      7'd83:
	  CASE_decode_inst_BITS_6_TO_0_3_NOT_decode_inst_ETC__q42 =
	      decode_inst[26:25] != 2'b0 && decode_inst[26:25] != 2'b01;
      default: CASE_decode_inst_BITS_6_TO_0_3_NOT_decode_inst_ETC__q42 =
		   decode_inst[6:0] != 7'd115 ||
		   decode_inst[14:12] == 3'b0 &&
		   decode_inst[31:25] != 7'h09 &&
		   immI__h32[11:0] != 12'h102 &&
		   immI__h32[11:0] != 12'h302 &&
		   immI__h32[11:0] != 12'h0 &&
		   immI__h32[11:0] != 12'h001 &&
		   immI__h32[11:0] != 12'h105;
    endcase
  end
endmodule  // module_decode

